package org.lianxianghui.weixindemo.find.find;

import java.util.ArrayList;
import androidx.appcompat.widget.AppCompatTextView;
import java.util.List;
import android.os.Bundle;
import org.lianxianghui.weixindemo.R;
import android.view.ViewGroup;
import androidx.recyclerview.widget.RecyclerView;
import android.view.View;
import android.content.Intent;
import androidx.constraintlayout.widget.ConstraintLayout;
import android.view.KeyEvent;
import android.widget.TextView;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.fragment.app.Fragment;
import android.view.LayoutInflater;

/**
* Generated by Sketch2Code
* Created by lianxianghui on 21-08-6.
*/

public class FindFragment extends Fragment {
    private static final String TAG = "FindFragment";
    private ConstraintLayout mContentView;
    private RecyclerView mListView;
    private ConstraintLayout mCustomNavigationBar;
    private View mBottomLine;
    private AppCompatTextView mTitle;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View v = inflater.inflate(R.layout.find_fragment, container, false);
 
        mContentView = (ConstraintLayout) v.findViewById(R.id.content_view);
        mListView = (RecyclerView) v.findViewById(R.id.list_view);
        mListView.setLayoutManager(new LinearLayoutManager(getActivity()));
        updateListView();
        mCustomNavigationBar = (ConstraintLayout) v.findViewById(R.id.custom_navigation_bar);
        mBottomLine = v.findViewById(R.id.bottom_line);
        mTitle = (AppCompatTextView) v.findViewById(R.id.title);
        return v;
    }

    private ListViewAdapter mListViewAdapter;
    private void updateListView() {
        List<Object> dataList  = getListViewDataList();
        mListViewAdapter = new ListViewAdapter(dataList);
        mListView.setAdapter(mListViewAdapter);
    }

    private List<Object> getListViewDataList() {
        ArrayList<Object> list = new ArrayList<Object>();

        FindCellData cellData0 = new FindCellData();
        cellData0.setCellId("0");
        cellData0.setCircle("find_find_cell_circle_5");
        cellData0.setRightHeadImage("find_find_cell_right_head_image_5");
        cellData0.setRightLabel("和张杰漂移抢福袋");
        cellData0.setRightIcon("find_find_cell_right_icon_5");
        cellData0.setRightLabelHidden(true);
        cellData0.setClickable(true);
        cellData0.setLeftImage("find_find_cell_left_image_5");
        cellData0.setName("朋友圈");
        list.add(cellData0);

        FindGapCellData cellData1 = new FindGapCellData();
        cellData1.setClickable(false);
        cellData1.setCellId("0");
        list.add(cellData1);

        FindCellData cellData2 = new FindCellData();
        cellData2.setCellId("1");
        cellData2.setRightHeadImageHidden(true);
        cellData2.setRightLabel(" ");
        cellData2.setRightIcon("find_find_cell_right_icon_4");
        cellData2.setCircleHidden(true);
        cellData2.setRightLabelHidden(true);
        cellData2.setClickable(true);
        cellData2.setLeftImage("find_find_cell_left_image_4");
        cellData2.setName("扫一扫");
        list.add(cellData2);

        FindCellData cellData3 = new FindCellData();
        cellData3.setCellId("2");
        cellData3.setRightHeadImageHidden(true);
        cellData3.setRightLabel("和张杰漂移抢福袋");
        cellData3.setRightIcon("find_find_cell_right_icon_3");
        cellData3.setCircleHidden(true);
        cellData3.setRightLabelHidden(true);
        cellData3.setClickable(true);
        cellData3.setLeftImage("find_find_cell_left_image_3");
        cellData3.setName("摇一摇");
        list.add(cellData3);

        FindGapCellData cellData4 = new FindGapCellData();
        cellData4.setClickable(false);
        cellData4.setCellId("1");
        list.add(cellData4);

        FindCellData cellData5 = new FindCellData();
        cellData5.setCellId("3");
        cellData5.setRightHeadImageHidden(true);
        cellData5.setRightLabel("和张杰漂移抢福袋");
        cellData5.setRightIcon("find_find_cell_right_icon_2");
        cellData5.setCircleHidden(true);
        cellData5.setRightLabelHidden(true);
        cellData5.setClickable(true);
        cellData5.setLeftImage("find_find_cell_left_image_2");
        cellData5.setName("看一看");
        list.add(cellData5);

        FindCellData cellData6 = new FindCellData();
        cellData6.setCellId("4");
        cellData6.setRightHeadImageHidden(true);
        cellData6.setRightLabel("和张杰漂移抢福袋");
        cellData6.setRightIcon("find_find_cell_right_icon_1");
        cellData6.setCircleHidden(true);
        cellData6.setRightLabelHidden(true);
        cellData6.setClickable(true);
        cellData6.setLeftImage("find_find_cell_left_image_1");
        cellData6.setName("搜一搜");
        list.add(cellData6);

        FindGapCellData cellData7 = new FindGapCellData();
        cellData7.setClickable(false);
        cellData7.setCellId("2");
        list.add(cellData7);

        FindCellData cellData8 = new FindCellData();
        cellData8.setCircleHidden(false);
        cellData8.setRightHeadImage("find_find_cell_right_head_image");
        cellData8.setCellId("5");
        cellData8.setClickable(true);
        cellData8.setRightLabelHidden(false);
        cellData8.setLeftImage("find_find_cell_left_image");
        cellData8.setRightHeadImageHidden(false);
        cellData8.setRightLabel("和张杰漂移抢福袋");
        cellData8.setCircle("find_find_cell_circle");
        cellData8.setRightIcon("find_find_cell_right_icon");
        cellData8.setName("游戏");
        list.add(cellData8);

        return list;
    }

    private class ListViewAdapter extends RecyclerView.Adapter<RecyclerView.ViewHolder> {
        private static final int ITEM_TYPE_FINDGAPCELL = 0;
        private static final int ITEM_TYPE_FINDCELL = 1;

        private List<Object> mDataList;

        public ListViewAdapter(List<Object> dataList) {
            mDataList = dataList;
        }

        @Override
        public RecyclerView.ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
            LayoutInflater layoutInflater = LayoutInflater.from(getActivity());
            if (viewType == ITEM_TYPE_FINDGAPCELL) 
                return new FindGapCellViewHolder(layoutInflater, parent);
            else if (viewType == ITEM_TYPE_FINDCELL) 
                return new FindCellViewHolder(layoutInflater, parent);
            else 
                return null;
        }

        @Override
        public void onBindViewHolder(RecyclerView.ViewHolder holder, int position) {
            Object data = mDataList.get(position);
            if (holder instanceof FindGapCellViewHolder)
                ((FindGapCellViewHolder) holder).bind((FindGapCellData)data);
            else if (holder instanceof FindCellViewHolder)
                ((FindCellViewHolder) holder).bind((FindCellData)data);
        }

        @Override
        public int getItemViewType(int position) {
            Object data = mDataList.get(position);
            if (data instanceof FindGapCellData)
                return ITEM_TYPE_FINDGAPCELL;
            else if (data instanceof FindCellData)
                return ITEM_TYPE_FINDCELL;
            else
                return -1;
        }

        @Override
        public int getItemCount() {
            return mDataList.size();
        }
    }


}




