package org.lianxianghui.weixindemo.find.find;

import androidx.recyclerview.widget.RecyclerView;
import android.view.ViewGroup;
import androidx.constraintlayout.widget.ConstraintLayout;
import org.lianxianghui.weixindemo.R;
import android.content.Intent;
import android.view.LayoutInflater;
import android.view.View;

/**
* Generated by Sketch2Code
* Created by lianxianghui on 21-08-6.
*/

public class FindGapCellViewHolder extends RecyclerView.ViewHolder implements View.OnClickListener {
    private FindGapCellData mFindGapCellData;


    public FindGapCellViewHolder(LayoutInflater inflater, ViewGroup parent) {
        super(inflater.inflate(R.layout.find_gap_cell, parent, false));
        View v = itemView;
    }

    public void bind(FindGapCellData findGapCell) {
        mFindGapCellData = findGapCell;
        boolean clickable = mFindGapCellData.getClickable();
        if (clickable) {
            itemView.setEnabled(true);
            itemView.setOnClickListener(this);
        } else {
            itemView.setEnabled(false);
            itemView.setOnClickListener(null);
        }
    }

    @Override
    public void onClick(View view) {

    }

}

class FindGapCellData {
    private boolean mClickable;
    private String mCellId;

    public boolean getClickable() {
        return mClickable;
    }

    public void setClickable(boolean clickable) {
        mClickable = clickable;
    }
    public String getCellId() {
        return mCellId;
    }

    public void setCellId(String cellId) {
        mCellId = cellId;
    }
}
