// LXHConversationListLoginStatusCell.h
// WeiXinDemo
//
//  Created by lianxianghui on 21-08-18
//  Generated by Sketch2Code
//  Copyright © 2021年 lianxianghui. All rights reserved.

#import <UIKit/UIKit.h>

@interface LXHConversationListLoginStatusCell : UIView

@property (nonatomic) UIImageView *statusImage;
@property (nonatomic) UILabel *statusLabel;

@end
