// LXHConversationListConversationCell.m
// WeiXinDemo
//
//  Created by lianxianghui on 21-08-18
//  Generated by Sketch2Code
//  Copyright © 2021年 lianxianghui. All rights reserved.


#import "LXHConversationListConversationCell.h"
#import "Masonry.h"

#define UIColorFromRGBA(rgbaValue) \
[UIColor colorWithRed:((rgbaValue & 0xFF000000) >> 24)/255.0 \
        green:((rgbaValue & 0x00FF0000) >>  16)/255.0 \
        blue:((rgbaValue & 0x0000FF00) >>  8)/255.0 \
        alpha:(rgbaValue & 0x000000FF)/255.0]

@interface LXHConversationListConversationCell()
@end

@implementation LXHConversationListConversationCell

- (instancetype)initWithFrame:(CGRect)frame {
    self = [super initWithFrame:frame];
    if (self) {
        self.backgroundColor = UIColorFromRGBA(0xFFFFFFFF);
        self.alpha = 1;
        [self addSubviews];
        [self makeConstraints];
    }
    return self;
}

- (void)addSubviews {
    [self addSubview:self.bottomLine];
    [self addSubview:self.noDisturbingImage];
    [self addSubview:self.time];
    [self addSubview:self.latestMessage];
    [self addSubview:self.title];
    [self addSubview:self.leftImage];
    [self addSubview:self.circle];
}

- (void)makeConstraints {
    [self.bottomLine mas_makeConstraints:^(MASConstraintMaker *make) {
        make.right.equalTo(self.mas_right);
        make.bottom.equalTo(self.mas_bottom);
        make.left.equalTo(self.leftImage.mas_left);
        make.height.mas_equalTo(0.5099999904632568);
    }];
    [self.noDisturbingImage mas_makeConstraints:^(MASConstraintMaker *make) {
        make.right.equalTo(self.mas_right).offset(-12);
        make.bottom.equalTo(self.mas_bottom).offset(-10);
        make.width.mas_equalTo(13);
        make.height.mas_equalTo(16);
    }];
    [self.time mas_makeConstraints:^(MASConstraintMaker *make) {
        make.right.equalTo(self.mas_right).offset(-12);
        make.top.equalTo(self.title.mas_top).offset(4);
    }];
    [self.latestMessage mas_makeConstraints:^(MASConstraintMaker *make) {
        make.bottom.equalTo(self.leftImage.mas_bottom).offset(-4);
        make.left.equalTo(self.title.mas_left);
    }];
    [self.title mas_makeConstraints:^(MASConstraintMaker *make) {
        make.top.equalTo(self.leftImage.mas_top).offset(-2);
        make.left.equalTo(self.leftImage.mas_right).offset(15);
        make.height.mas_equalTo(23);
    }];
    [self.leftImage mas_makeConstraints:^(MASConstraintMaker *make) {
        make.left.equalTo(self.mas_left).offset(8);
        make.centerY.equalTo(self.mas_centerY);
        make.width.mas_equalTo(44);
        make.height.mas_equalTo(44);
    }];
    [self.circle mas_makeConstraints:^(MASConstraintMaker *make) {
        make.centerY.equalTo(self.leftImage.mas_top);
        make.centerX.equalTo(self.leftImage.mas_right);
        make.height.mas_equalTo(8);
        make.width.mas_equalTo(8);
    }];
}

//Getters
- (UIView *)bottomLine {
    if (!_bottomLine) {
        _bottomLine = [[UIView alloc] init];
        _bottomLine.backgroundColor = UIColorFromRGBA(0xD8D8D8FF);
        _bottomLine.alpha = 1;
    }
    return _bottomLine;
}

- (UIImageView *)noDisturbingImage {
    if (!_noDisturbingImage) {
        _noDisturbingImage = [[UIImageView alloc] init];
        _noDisturbingImage.alpha = 1;
        _noDisturbingImage.image = [UIImage imageNamed:@"weixin_conversationlist_no_disturbing_image"];
    }
    return _noDisturbingImage;
}

- (UILabel *)time {
    if (!_time) {
        _time = [[UILabel alloc] init];
        _time.backgroundColor = UIColorFromRGBA(0xFFFFFF00);
        _time.alpha = 1;

        _time.numberOfLines = 0;
        UIFont *font = [UIFont fontWithName:@"PingFangSC-Regular" size:11];
        if (!font) font = [UIFont systemFontOfSize:11];

        NSMutableDictionary *textAttributes = [NSMutableDictionary dictionary];
        [textAttributes setObject:UIColorFromRGBA(0x9E9E9EFF) forKey:NSForegroundColorAttributeName];
        [textAttributes setObject:font forKey:NSFontAttributeName];
        [textAttributes setObject:@(-0.623) forKey:NSKernAttributeName];
        NSAttributedString *text = [[NSAttributedString alloc] initWithString:NSLocalizedString(@"下午7:18", nil) attributes:textAttributes];
        _time.attributedText = text;
        _time.textAlignment = NSTextAlignmentNatural;
    }
    return _time;
}

- (UILabel *)latestMessage {
    if (!_latestMessage) {
        _latestMessage = [[UILabel alloc] init];
        _latestMessage.backgroundColor = UIColorFromRGBA(0xFFFFFF00);
        _latestMessage.alpha = 1;

        _latestMessage.numberOfLines = 0;
        UIFont *font = [UIFont fontWithName:@"PingFangSC-Regular" size:12];
        if (!font) font = [UIFont systemFontOfSize:12];

        NSMutableDictionary *textAttributes = [NSMutableDictionary dictionary];
        [textAttributes setObject:UIColorFromRGBA(0x9E9E9EFF) forKey:NSForegroundColorAttributeName];
        [textAttributes setObject:font forKey:NSFontAttributeName];
        [textAttributes setObject:@(-0.534) forKey:NSKernAttributeName];
        NSAttributedString *text = [[NSAttributedString alloc] initWithString:NSLocalizedString(@"摄影师丰枫：这个可以有", nil) attributes:textAttributes];
        _latestMessage.attributedText = text;
        _latestMessage.textAlignment = NSTextAlignmentNatural;
    }
    return _latestMessage;
}

- (UILabel *)title {
    if (!_title) {
        _title = [[UILabel alloc] init];
        _title.backgroundColor = UIColorFromRGBA(0xFFFFFF00);
        _title.alpha = 1;

        _title.numberOfLines = 0;
        UIFont *font = [UIFont fontWithName:@"PingFangSC-Regular" size:14];
        if (!font) font = [UIFont systemFontOfSize:14];

        NSMutableDictionary *textAttributes = [NSMutableDictionary dictionary];
        [textAttributes setObject:UIColorFromRGBA(0x1B1B1BFF) forKey:NSForegroundColorAttributeName];
        [textAttributes setObject:font forKey:NSFontAttributeName];
        [textAttributes setObject:@(-0.623) forKey:NSKernAttributeName];
        NSAttributedString *text = [[NSAttributedString alloc] initWithString:NSLocalizedString(@"运动旅游活动群", nil) attributes:textAttributes];
        _title.attributedText = text;
        _title.textAlignment = NSTextAlignmentLeft;
    }
    return _title;
}

- (UIImageView *)leftImage {
    if (!_leftImage) {
        _leftImage = [[UIImageView alloc] init];
        _leftImage.alpha = 1;
        _leftImage.image = [UIImage imageNamed:@"weixin_conversationlist_group_image"];
    }
    return _leftImage;
}

- (UIView *)circle {
    if (!_circle) {
        _circle = [[UIView alloc] init];
        _circle.backgroundColor = UIColorFromRGBA(0xFF0008FF);
        _circle.layer.cornerRadius = 3.999999999999991;
        _circle.alpha = 1;
    }
    return _circle;
}


@end

