// LXHConversationListViewModel.m
// WeiXinDemo
//
//  Created by lianxianghui on 21-08-18
//  Generated by Sketch2Code
//  Copyright © 2021年 lianxianghui. All rights reserved.


#import "LXHConversationListViewModel.h"

@interface LXHConversationListViewModel ()
@property (nonatomic) NSMutableArray *cellDataArrayForListView;
@end

@implementation LXHConversationListViewModel

- (instancetype)init {
    self = [super init];
    if (self) {
    }
    return self;
}

- (NSMutableArray *)cellDataArrayForListView {
    if (!_cellDataArrayForListView) {
        _cellDataArrayForListView = [NSMutableArray array];
        NSDictionary *dic = nil;
        dic = @{@"statusLabel":@"Mac微信已登录，手机通知已关闭", @"cellId":@"0", @"clickable":@"1", @"statusImage":@"weixin_conversation_list_login_status_cell_status_image", @"cellType":@"LXHConversationListLoginStatusCell"};
        [_cellDataArrayForListView addObject:dic];
        dic = @{@"cellId":@"0", @"noDisturbingImageHidden":@"0", @"noDisturbingImage":@"weixin_conversationlist_no_disturbing_image", @"time":@"下午7:18", @"latestMessageHidden":@"0", @"title":@"运动旅游活动群", @"latestMessage":@"摄影师丰枫：这个可以有", @"circleHidden":@"0", @"clickable":@"1", @"leftImage":@"weixin_conversationlist_group_image", @"cellType":@"LXHConversationListConversationCell"};
        [_cellDataArrayForListView addObject:dic];
        dic = @{@"cellId":@"1", @"noDisturbingImageHidden":@"0", @"noDisturbingImage":@"weixin_conversationlist_no_disturbing_image", @"time":@"下午10:41", @"title":@"订阅号", @"latestMessage":@"晨光图书礼品：平安夜 | 真平安", @"clickable":@"1", @"leftImage":@"weixin_conversationlist_subscription_image", @"cellType":@"LXHConversationListConversationCell"};
        [_cellDataArrayForListView addObject:dic];
        dic = @{@"cellId":@"2", @"noDisturbingImageHidden":@"1", @"noDisturbingImage":@"weixin_conversation_list_conversation_cell_no_disturbing_image", @"time":@"上午8:49", @"latestMessageHidden":@"1", @"title":@"文件传输助手", @"latestMessage":@" ", @"circleHidden":@"1", @"clickable":@"1", @"leftImage":@"weixin_conversationlist_file_transfer", @"cellType":@"LXHConversationListConversationCell"};
        [_cellDataArrayForListView addObject:dic];
        dic = @{@"cellId":@"3", @"noDisturbingImageHidden":@"1", @"noDisturbingImage":@"weixin_conversation_list_conversation_cell_no_disturbing_image", @"time":@"下午5:16", @"title":@"连向辉", @"latestMessage":@"[图片]", @"clickable":@"1", @"leftImage":@"weixin_conversationlist_person_image", @"cellType":@"LXHConversationListConversationCell"};
        [_cellDataArrayForListView addObject:dic];
        dic = @{@"cellId":@"4", @"noDisturbingImageHidden":@"0", @"noDisturbingImage":@"weixin_conversationlist_no_disturbing_image", @"time":@"下午7:18", @"title":@"运动旅游活动群", @"latestMessage":@"摄影师丰枫：这个可以有", @"clickable":@"1", @"leftImage":@"weixin_conversationlist_group_image", @"cellType":@"LXHConversationListConversationCell"};
        [_cellDataArrayForListView addObject:dic];
        dic = @{@"cellId":@"5", @"noDisturbingImageHidden":@"0", @"noDisturbingImage":@"weixin_conversationlist_no_disturbing_image", @"time":@"下午7:18", @"title":@"运动旅游活动群", @"latestMessage":@"摄影师丰枫：这个可以有", @"clickable":@"1", @"leftImage":@"weixin_conversationlist_group_image", @"cellType":@"LXHConversationListConversationCell"};
        [_cellDataArrayForListView addObject:dic];
        dic = @{@"cellId":@"6", @"noDisturbingImageHidden":@"0", @"noDisturbingImage":@"weixin_conversationlist_no_disturbing_image", @"time":@"下午7:18", @"title":@"运动旅游活动群", @"latestMessage":@"摄影师丰枫：这个可以有", @"clickable":@"1", @"leftImage":@"weixin_conversationlist_group_image", @"cellType":@"LXHConversationListConversationCell"};
        [_cellDataArrayForListView addObject:dic];
        dic = @{@"cellId":@"7", @"noDisturbingImageHidden":@"0", @"noDisturbingImage":@"weixin_conversationlist_no_disturbing_image", @"time":@"下午7:18", @"title":@"运动旅游活动群", @"latestMessage":@"摄影师丰枫：这个可以有", @"clickable":@"1", @"leftImage":@"weixin_conversationlist_group_image", @"cellType":@"LXHConversationListConversationCell"};
        [_cellDataArrayForListView addObject:dic];
        dic = @{@"cellId":@"8", @"noDisturbingImageHidden":@"0", @"noDisturbingImage":@"weixin_conversationlist_no_disturbing_image", @"time":@"下午7:18", @"title":@"运动旅游活动群", @"latestMessage":@"摄影师丰枫：这个可以有", @"clickable":@"1", @"leftImage":@"weixin_conversationlist_group_image", @"cellType":@"LXHConversationListConversationCell"};
        [_cellDataArrayForListView addObject:dic];
    }
    return _cellDataArrayForListView;
}


@end
