// LXHConversationListConversationCell.h
// WeiXinDemo
//
//  Created by lianxianghui on 21-08-18
//  Generated by Sketch2Code
//  Copyright © 2021年 lianxianghui. All rights reserved.

#import <UIKit/UIKit.h>

@interface LXHConversationListConversationCell : UIView

@property (nonatomic) UIView *bottomLine;
@property (nonatomic) UIImageView *noDisturbingImage;
@property (nonatomic) UILabel *time;
@property (nonatomic) UILabel *latestMessage;
@property (nonatomic) UILabel *title;
@property (nonatomic) UIImageView *leftImage;
@property (nonatomic) UIView *circle;

@end
