// LXHConversationListView.h
// WeiXinDemo
//
//  Created by lianxianghui on 21-08-18
//  Generated by Sketch2Code
//  Copyright © 2021年 lianxianghui. All rights reserved.

#import <UIKit/UIKit.h>

@interface LXHConversationListView : UIView

@property (nonatomic) UITableView *listView;
@property (nonatomic) UIView *customNavigationBar;
@property (nonatomic) UIView *bottomLine;
@property (nonatomic) UIButton *rightButton;
@property (nonatomic) UIImageView *addIcon;
@property (nonatomic) UIView *circle;
@property (nonatomic) UILabel *title;

@end
