// LXHFindViewModel.m
// WeiXinDemo
//
//  Created by lianxianghui on 21-08-9
//  Generated by Sketch2Code
//  Copyright © 2021年 lianxianghui. All rights reserved.


#import "LXHFindViewModel.h"

@interface LXHFindViewModel ()
@property (nonatomic) NSMutableArray *cellDataArrayForListView;
@end

@implementation LXHFindViewModel

- (instancetype)init {
    self = [super init];
    if (self) {
    }
    return self;
}

- (NSMutableArray *)cellDataArrayForListView {
    if (!_cellDataArrayForListView) {
        _cellDataArrayForListView = [NSMutableArray array];
        NSDictionary *dic = nil;
        dic = @{@"cellId":@"0", @"circle":@"find_find_cell_circle_5", @"rightHeadImage":@"find_find_cell_right_head_image_5", @"rightLabel":@"和张杰漂移抢福袋", @"rightIcon":@"find_find_cell_right_icon_5", @"rightLabelHidden":@"1", @"clickable":@"1", @"leftImage":@"find_find_cell_left_image_5", @"name":@"朋友圈", @"cellType":@"LXHFindCell"};
        [_cellDataArrayForListView addObject:dic];
        dic = @{@"clickable":@"0", @"cellId":@"0", @"cellType":@"LXHFindGapCell"};
        [_cellDataArrayForListView addObject:dic];
        dic = @{@"cellId":@"1", @"rightHeadImageHidden":@"1", @"rightLabel":@" ", @"rightIcon":@"find_find_cell_right_icon_4", @"circleHidden":@"1", @"rightLabelHidden":@"1", @"clickable":@"1", @"leftImage":@"find_find_cell_left_image_4", @"name":@"扫一扫", @"cellType":@"LXHFindCell"};
        [_cellDataArrayForListView addObject:dic];
        dic = @{@"cellId":@"2", @"rightHeadImageHidden":@"1", @"rightLabel":@"和张杰漂移抢福袋", @"rightIcon":@"find_find_cell_right_icon_3", @"circleHidden":@"1", @"rightLabelHidden":@"1", @"clickable":@"1", @"leftImage":@"find_find_cell_left_image_3", @"name":@"摇一摇", @"cellType":@"LXHFindCell"};
        [_cellDataArrayForListView addObject:dic];
        dic = @{@"clickable":@"0", @"cellId":@"1", @"cellType":@"LXHFindGapCell"};
        [_cellDataArrayForListView addObject:dic];
        dic = @{@"cellId":@"3", @"rightHeadImageHidden":@"1", @"rightLabel":@"和张杰漂移抢福袋", @"rightIcon":@"find_find_cell_right_icon_2", @"circleHidden":@"1", @"rightLabelHidden":@"1", @"clickable":@"1", @"leftImage":@"find_find_cell_left_image_2", @"name":@"看一看", @"cellType":@"LXHFindCell"};
        [_cellDataArrayForListView addObject:dic];
        dic = @{@"cellId":@"4", @"rightHeadImageHidden":@"1", @"rightLabel":@"和张杰漂移抢福袋", @"rightIcon":@"find_find_cell_right_icon_1", @"circleHidden":@"1", @"rightLabelHidden":@"1", @"clickable":@"1", @"leftImage":@"find_find_cell_left_image_1", @"name":@"搜一搜", @"cellType":@"LXHFindCell"};
        [_cellDataArrayForListView addObject:dic];
        dic = @{@"clickable":@"0", @"cellId":@"2", @"cellType":@"LXHFindGapCell"};
        [_cellDataArrayForListView addObject:dic];
        dic = @{@"circleHidden":@"0", @"rightHeadImage":@"find_find_cell_right_head_image", @"cellId":@"5", @"clickable":@"1", @"rightLabelHidden":@"0", @"leftImage":@"find_find_cell_left_image", @"cellType":@"LXHFindCell", @"rightHeadImageHidden":@"0", @"rightLabel":@"和张杰漂移抢福袋", @"circle":@"find_find_cell_circle", @"rightIcon":@"find_find_cell_right_icon", @"name":@"游戏"};
        [_cellDataArrayForListView addObject:dic];
    }
    return _cellDataArrayForListView;
}


@end
