// LXHFindCell.h
// WeiXinDemo
//
//  Created by lianxianghui on 21-08-9
//  Generated by Sketch2Code
//  Copyright © 2021年 lianxianghui. All rights reserved.

#import <UIKit/UIKit.h>

@interface LXHFindCell : UIView

@property (nonatomic) UIView *bottomLine;
@property (nonatomic) UIImageView *leftImage;
@property (nonatomic) UILabel *name;
@property (nonatomic) UIImageView *rightIcon;
@property (nonatomic) UIImageView *rightHeadImage;
@property (nonatomic) UIImageView *circle;
@property (nonatomic) UILabel *rightLabel;

@end
