// LXHFindViewController.m
// WeiXinDemo
//
//  Created by lianxianghui on 21-08-9
//  Generated by Sketch2Code
//  Copyright © 2021年 lianxianghui. All rights reserved.

#import "LXHFindViewController.h"
#import "LXHFindView.h"
#import "LXHFindViewModel.h"
#import "LXHFindCell.h"
#import "LXHFindGapCell.h"
#import "Masonry.h"

#define UIColorFromRGBA(rgbaValue) \
[UIColor colorWithRed:((rgbaValue & 0xFF000000) >> 24)/255.0 \
        green:((rgbaValue & 0x00FF0000) >>  16)/255.0 \
        blue:((rgbaValue & 0x0000FF00) >>  8)/255.0 \
        alpha:(rgbaValue & 0x000000FF)/255.0]
    
@interface LXHFindViewController() <UITableViewDataSource, UITableViewDelegate>
@property (nonatomic) LXHFindView *contentView;
@property (nonatomic) LXHFindViewModel *viewModel;
@end

@implementation LXHFindViewController

- (instancetype)initWithViewModel:(id)viewModel {
    self = [super init];
    if (self) {
        self.viewModel = viewModel;
    }
    return self;
}

- (void)viewDidLoad {
    [super viewDidLoad];
    self.view.backgroundColor = UIColorFromRGBA(0x38363CFF);
    [self.navigationController setNavigationBarHidden:YES animated:NO];
    self.automaticallyAdjustsScrollViewInsets = NO;
    self.contentView = [[LXHFindView alloc] init];
    [self.view addSubview:self.contentView];
    [self.contentView mas_makeConstraints:^(MASConstraintMaker *make) {
        make.top.equalTo(self.mas_topLayoutGuideBottom);
        make.left.right.equalTo(self.view);
        make.bottom.equalTo(self.mas_bottomLayoutGuideTop);
    }];
    UISwipeGestureRecognizer *swipeRecognizer = [[UISwipeGestureRecognizer alloc] initWithTarget:self action:@selector(swipeView:)];
    [self.view addGestureRecognizer:swipeRecognizer];
    [self addActions];
    [self setDelegates];
}

- (void)swipeView:(id)sender {
    [self.navigationController popViewControllerAnimated:YES];
}

- (UIStatusBarStyle)preferredStatusBarStyle {
    return UIStatusBarStyleLightContent;
}

- (void)addActions {
}

- (void)setDelegates {
    self.contentView.listView.dataSource = self;
    self.contentView.listView.delegate = self;
}
//Delegate Methods
- (NSArray *)dataForTableView:(UITableView *)tableView {
    if (tableView == self.contentView.listView) {
        return [self.viewModel cellDataArrayForListView];
    }
    return nil;
}

- (id)cellDataForTableView:(UITableView *)tableView atIndexPath:(NSIndexPath *)indexPath {
    NSArray *dataForTableView = [self dataForTableView:tableView];
    if (indexPath.row < dataForTableView.count)
        return [dataForTableView objectAtIndex:indexPath.row];
    else
        return nil;
}

- (NSString *)tableView:(UITableView *)tableView cellTypeAtIndexPath:(NSIndexPath *)indexPath {
    NSArray *data = [self dataForTableView:tableView];
    if (indexPath.row < data.count) {
        NSDictionary *cellData = [data objectAtIndex:indexPath.row];
        return [cellData valueForKey:@"cellType"];
    }
    return nil;
}

- (NSInteger)tableView:(UITableView *)tableView viewTagAtIndexPath:(NSIndexPath *)indexPath {
    NSString *cellType = [self tableView:tableView cellTypeAtIndexPath:indexPath];
    if ([cellType isEqualToString:@"LXHFindCell"])
        return 100;
    if ([cellType isEqualToString:@"LXHFindGapCell"])
        return 101;
    return -1;
}

- (NSString *)tableView:(UITableView *)tableView cellContentViewClassStingAtIndexPath:(NSIndexPath *)indexPath {
    NSString *cellType = [self tableView:tableView cellTypeAtIndexPath:indexPath];
    NSString *classString = cellType;
    return classString;
}

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
    return [self dataForTableView:tableView].count;
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    NSString *cellType = [self tableView:tableView cellTypeAtIndexPath:indexPath];
    UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:cellType];
    NSInteger tag = [self tableView:tableView viewTagAtIndexPath:indexPath];
    id dataForRow = [self cellDataForTableView:tableView atIndexPath:indexPath];
    if (!cell) {
        cell = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:cellType];
        NSString *viewClass = [self tableView:tableView cellContentViewClassStingAtIndexPath:indexPath];
        UIView *view = [[NSClassFromString(viewClass) alloc] init];
        view.tag = tag;
        [cell.contentView addSubview:view];
        cell.contentView.backgroundColor = [UIColor clearColor];
        cell.backgroundColor = [UIColor clearColor];
        [view mas_makeConstraints:^(MASConstraintMaker *make) {
            make.edges.equalTo(cell.contentView);
        }];
        NSString *clickable = [dataForRow valueForKey:@"clickable"];
        if ([clickable isEqualToString:@"0"])
            cell.selectionStyle = UITableViewCellSelectionStyleNone;
    }
    UIView *view = [cell.contentView viewWithTag:tag];
    if ([cellType isEqualToString:@"LXHFindCell"]) {
        LXHFindCell *cellView = (LXHFindCell *)view;
        NSString *name = [dataForRow valueForKey:@"name"];
        if (!name || [name isEqualToString:@""])
            name = @" "; //must have character
        NSMutableAttributedString *nameAttributedString = [cellView.name.attributedText mutableCopy];
        if (nameAttributedString && ![name isEqualToString:nameAttributedString.string]) {
            [nameAttributedString.mutableString setString:name];
            cellView.name.attributedText = nameAttributedString;
        }

        NSString *rightLabel = [dataForRow valueForKey:@"rightLabel"];
        if (!rightLabel || [rightLabel isEqualToString:@""])
            rightLabel = @" "; //must have character
        NSMutableAttributedString *rightLabelAttributedString = [cellView.rightLabel.attributedText mutableCopy];
        if (rightLabelAttributedString && ![rightLabel isEqualToString:rightLabelAttributedString.string]) {
            [rightLabelAttributedString.mutableString setString:rightLabel];
            cellView.rightLabel.attributedText = rightLabelAttributedString;
        }

        NSString *leftImageImageName = [dataForRow valueForKey:@"leftImage"];
        if (leftImageImageName)
            cellView.leftImage.image = [UIImage imageNamed:leftImageImageName];

        NSString *rightIconImageName = [dataForRow valueForKey:@"rightIcon"];
        if (rightIconImageName)
            cellView.rightIcon.image = [UIImage imageNamed:rightIconImageName];

        NSString *rightHeadImageImageName = [dataForRow valueForKey:@"rightHeadImage"];
        if (rightHeadImageImageName)
            cellView.rightHeadImage.image = [UIImage imageNamed:rightHeadImageImageName];

        NSString *circleImageName = [dataForRow valueForKey:@"circle"];
        if (circleImageName)
            cellView.circle.image = [UIImage imageNamed:circleImageName];

        cellView.rightLabel.hidden = [[dataForRow valueForKey:@"rightLabelHidden"] boolValue];
        cellView.rightHeadImage.hidden = [[dataForRow valueForKey:@"rightHeadImageHidden"] boolValue];
        cellView.circle.hidden = [[dataForRow valueForKey:@"circleHidden"] boolValue];
    }
    if ([cellType isEqualToString:@"LXHFindGapCell"]) {
        LXHFindGapCell *cellView = (LXHFindGapCell *)view;
    }

    return cell;
}

- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath {
    NSString *cellType = [self tableView:tableView cellTypeAtIndexPath:indexPath];
    if ([cellType isEqualToString:@"LXHFindCell"])
        return 40;
    if ([cellType isEqualToString:@"LXHFindGapCell"])
        return 20;
    return 0;
}

- (NSIndexPath *)tableView:(UITableView *)tableView willSelectRowAtIndexPath:(NSIndexPath *)indexPath {
    id dataForRow = [self cellDataForTableView:tableView atIndexPath:indexPath];
    NSString *clickable = [dataForRow valueForKey:@"clickable"];
    if ([clickable isEqualToString:@"0"])
        return nil;
    else
        return indexPath;
}

- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath {
    [tableView deselectRowAtIndexPath:indexPath animated:YES];
    if (tableView == self.contentView.listView) {
        switch(indexPath.row) {
            default:
                break;
        }
    }
}


@end
