// LXHContactsIndexCell.h
// WeiXinDemo
//
//  Created by lianxianghui on 21-08-9
//  Generated by Sketch2Code
//  Copyright © 2021年 lianxianghui. All rights reserved.

#import <UIKit/UIKit.h>

@interface LXHContactsIndexCell : UIView

@property (nonatomic) UILabel *label;

@end
