// LXHContactsView.m
// WeiXinDemo
//
//  Created by lianxianghui on 21-08-9
//  Generated by Sketch2Code
//  Copyright © 2021年 lianxianghui. All rights reserved.


#import "LXHContactsView.h"
#import "Masonry.h"

#define UIColorFromRGBA(rgbaValue) \
[UIColor colorWithRed:((rgbaValue & 0xFF000000) >> 24)/255.0 \
        green:((rgbaValue & 0x00FF0000) >>  16)/255.0 \
        blue:((rgbaValue & 0x0000FF00) >>  8)/255.0 \
        alpha:(rgbaValue & 0x000000FF)/255.0]

@interface LXHContactsView()
@end

@implementation LXHContactsView

- (instancetype)initWithFrame:(CGRect)frame {
    self = [super initWithFrame:frame];
    if (self) {
        self.backgroundColor = UIColorFromRGBA(0xEFEFF4FF);
        self.alpha = 1;
        [self addSubviews];
        [self makeConstraints];
    }
    return self;
}

- (void)addSubviews {
    [self addSubview:self.listView];
    [self addSubview:self.customNavigationBar];
}

- (void)makeConstraints {
    [self.listView mas_makeConstraints:^(MASConstraintMaker *make) {
        make.left.equalTo(self.mas_left);
        make.right.equalTo(self.mas_right);
        make.bottom.equalTo(self.mas_bottom);
        make.top.equalTo(self.customNavigationBar.mas_bottom);
    }];
    [self.customNavigationBar mas_makeConstraints:^(MASConstraintMaker *make) {
        make.left.equalTo(self.mas_left);
        make.right.equalTo(self.mas_right);
        make.top.equalTo(self.mas_top);
        make.height.mas_equalTo(45);
    }];
    [self.bottomLine mas_makeConstraints:^(MASConstraintMaker *make) {
        make.left.equalTo(self.customNavigationBar.mas_left);
        make.right.equalTo(self.customNavigationBar.mas_right);
        make.bottom.equalTo(self.customNavigationBar.mas_bottom);
        make.height.mas_equalTo(0.5099999904632568);
    }];
    [self.rightButton mas_makeConstraints:^(MASConstraintMaker *make) {
        make.top.equalTo(self.customNavigationBar.mas_top);
        make.right.equalTo(self.customNavigationBar.mas_right);
        make.height.mas_equalTo(44);
        make.width.mas_equalTo(60);
    }];
    [self.Image mas_makeConstraints:^(MASConstraintMaker *make) {
        make.height.mas_equalTo(23);
        make.width.mas_equalTo(25.29999923706055);
        make.centerY.equalTo(self.rightButton.mas_centerY).offset(2);
        make.centerX.equalTo(self.rightButton.mas_centerX).offset(2);
    }];
    [self.title mas_makeConstraints:^(MASConstraintMaker *make) {
        make.centerX.equalTo(self.customNavigationBar.mas_centerX);
        make.centerY.equalTo(self.customNavigationBar.mas_centerY);
    }];
}

//Getters
- (UITableView *)listView {
    if (!_listView) {
        _listView = [[UITableView alloc] initWithFrame:CGRectZero style:UITableViewStylePlain];
        _listView.backgroundColor = UIColorFromRGBA(0xEFEFF4FF);
        _listView.alpha = 1;
        _listView.tableFooterView = [UIView new];
        _listView.separatorStyle = UITableViewCellSeparatorStyleNone;
    }
    return _listView;
}

- (UIView *)customNavigationBar {
    if (!_customNavigationBar) {
        _customNavigationBar = [[UIView alloc] init];
        _customNavigationBar.backgroundColor = UIColorFromRGBA(0x38363CFF);
        _customNavigationBar.alpha = 1;
        [_customNavigationBar addSubview:self.bottomLine];
        [_customNavigationBar addSubview:self.rightButton];
        [_customNavigationBar addSubview:self.title];
    }
    return _customNavigationBar;
}

- (UIView *)bottomLine {
    if (!_bottomLine) {
        _bottomLine = [[UIView alloc] init];
        _bottomLine.backgroundColor = UIColorFromRGBA(0xB2B2B2FF);
        _bottomLine.alpha = 1;
    }
    return _bottomLine;
}

- (UIButton *)rightButton {
    if (!_rightButton) {
        _rightButton = [UIButton buttonWithType:UIButtonTypeCustom];
        _rightButton.backgroundColor = UIColorFromRGBA(0xFFFFFF00);
        _rightButton.alpha = 1;

        [_rightButton addSubview:self.Image];
        [_rightButton addTarget:self action:@selector(rightButtonTouchDown:) forControlEvents:UIControlEventTouchDown];
        [_rightButton addTarget:self action:@selector(rightButtonTouchUpOutside:) forControlEvents:UIControlEventTouchUpOutside];
        [_rightButton addTarget:self action:@selector(rightButtonTouchUpInside:) forControlEvents:UIControlEventTouchUpInside];
    }
    return _rightButton;
}

- (UIImageView *)Image {
    if (!_Image) {
        _Image = [[UIImageView alloc] init];
        _Image.alpha = 1;
        _Image.image = [UIImage imageNamed:@"contacts_contacts_view_image"];
    }
    return _Image;
}

- (UILabel *)title {
    if (!_title) {
        _title = [[UILabel alloc] init];
        _title.backgroundColor = UIColorFromRGBA(0xFFFFFF00);
        _title.alpha = 1;

        _title.numberOfLines = 0;
        UIFont *font = [UIFont fontWithName:@".SFUIText-Light" size:17];
        if (!font) font = [UIFont systemFontOfSize:17];

        NSMutableDictionary *textAttributes = [NSMutableDictionary dictionary];
        [textAttributes setObject:UIColorFromRGBA(0xF6F6F6FF) forKey:NSForegroundColorAttributeName];
        [textAttributes setObject:font forKey:NSFontAttributeName];
        [textAttributes setObject:@(-0.41) forKey:NSKernAttributeName];
        NSAttributedString *text = [[NSAttributedString alloc] initWithString:NSLocalizedString(@"通讯录", nil) attributes:textAttributes];
        _title.attributedText = text;
        _title.textAlignment = NSTextAlignmentCenter;
    }
    return _title;
}

//Actions
- (void)rightButtonTouchDown:(UIButton *)sender {
    sender.alpha = 0.5;
}

- (void)rightButtonTouchUpOutside:(UIButton *)sender {
    sender.alpha = 1;
}

- (void)rightButtonTouchUpInside:(UIButton *)sender {
    sender.alpha = 1;
}

@end

