// LXHContactsViewModel.h
// WeiXinDemo
//
//  Created by lianxianghui on 21-08-9
//  Generated by Sketch2Code
//  Copyright © 2021年 lianxianghui. All rights reserved.

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

@interface LXHContactsViewModel : NSObject

- (NSMutableArray *)cellDataArrayForListView;
@end

NS_ASSUME_NONNULL_END
