package org.lianxianghui.weixindemo.contacts.contacts;

import androidx.recyclerview.widget.RecyclerView;
import android.view.ViewGroup;
import androidx.appcompat.widget.AppCompatTextView;
import androidx.constraintlayout.widget.ConstraintLayout;
import android.widget.TextView;
import org.lianxianghui.weixindemo.R;
import android.content.Intent;
import android.view.KeyEvent;
import android.view.LayoutInflater;
import android.view.View;

/**
* Generated by Sketch2Code
* Created by lianxianghui on 21-08-18.
*/

public class ContactsIndexCellViewHolder extends RecyclerView.ViewHolder {
    private ContactsIndexCellData contactsIndexCellData;

    public final AppCompatTextView label;

    public ContactsIndexCellViewHolder(LayoutInflater inflater, ViewGroup parent) {
        super(inflater.inflate(R.layout.contacts_index_cell, parent, false));
        View v = itemView;
        label = (AppCompatTextView) v.findViewById(R.id.label);
    }

    public void bind(ContactsIndexCellData contactsIndexCellData) {
        this.contactsIndexCellData = contactsIndexCellData;
        label.setText(contactsIndexCellData.getLabel());
        boolean clickable = contactsIndexCellData.getClickable();
        if (clickable) {
            itemView.setEnabled(true);
        } else {
            itemView.setEnabled(false);
        }
    }

    public ContactsIndexCellData getContactsIndexCellData() {
        return contactsIndexCellData;
    }


}

class ContactsIndexCellData {
    private String label;
    private String cellId;
    private boolean clickable;

    public String getLabel() {
        return label;
    }
    public void setLabel(String label) {
        this.label = label;
    }

    public String getCellId() {
        return cellId;
    }
    public void setCellId(String cellId) {
        this.cellId = cellId;
    }

    public boolean getClickable() {
        return clickable;
    }
    public void setClickable(boolean clickable) {
        this.clickable = clickable;
    }

}
