package org.lianxianghui.weixindemo.contacts.contacts;

import androidx.recyclerview.widget.RecyclerView;
import android.view.ViewGroup;
import androidx.appcompat.widget.AppCompatTextView;
import androidx.constraintlayout.widget.ConstraintLayout;
import android.widget.TextView;
import org.lianxianghui.weixindemo.R;
import android.content.Intent;
import android.view.KeyEvent;
import android.view.LayoutInflater;
import android.view.View;

/**
* Generated by Sketch2Code
* Created by lianxianghui on 21-08-6.
*/

public class ContactsIndexCellViewHolder extends RecyclerView.ViewHolder implements View.OnClickListener {
    private ContactsIndexCellData mContactsIndexCellData;

    private AppCompatTextView mLabel;

    public ContactsIndexCellViewHolder(LayoutInflater inflater, ViewGroup parent) {
        super(inflater.inflate(R.layout.contacts_index_cell, parent, false));
        View v = itemView;
        mLabel = (AppCompatTextView) v.findViewById(R.id.label);
    }

    public void bind(ContactsIndexCellData contactsIndexCell) {
        mContactsIndexCellData = contactsIndexCell;
        mLabel.setText(mContactsIndexCellData.getLabel());
        boolean clickable = mContactsIndexCellData.getClickable();
        if (clickable) {
            itemView.setEnabled(true);
            itemView.setOnClickListener(this);
        } else {
            itemView.setEnabled(false);
            itemView.setOnClickListener(null);
        }
    }

    @Override
    public void onClick(View view) {

    }


}

class ContactsIndexCellData {
    private String mLabel;
    private String mCellId;
    private boolean mClickable;

    public String getLabel() {
        return mLabel;
    }

    public void setLabel(String label) {
        mLabel = label;
    }
    public String getCellId() {
        return mCellId;
    }

    public void setCellId(String cellId) {
        mCellId = cellId;
    }
    public boolean getClickable() {
        return mClickable;
    }

    public void setClickable(boolean clickable) {
        mClickable = clickable;
    }
}
