package org.lianxianghui.weixindemo.contacts.contacts;

import androidx.appcompat.widget.AppCompatTextView;
import org.lianxianghui.weixindemo.R;
import android.graphics.BitmapFactory;
import androidx.core.graphics.drawable.RoundedBitmapDrawableFactory;
import android.view.ViewGroup;
import androidx.recyclerview.widget.RecyclerView;
import android.view.View;
import android.content.Intent;
import androidx.appcompat.widget.AppCompatImageView;
import android.view.KeyEvent;
import android.graphics.Bitmap;
import android.widget.TextView;
import androidx.constraintlayout.widget.ConstraintLayout;
import android.view.LayoutInflater;
import androidx.core.graphics.drawable.RoundedBitmapDrawable;

/**
* Generated by Sketch2Code
* Created by lianxianghui on 21-08-6.
*/

public class ContactCellViewHolder extends RecyclerView.ViewHolder implements View.OnClickListener {
    private ContactCellData mContactCellData;

    private View mBottomLine;
    private AppCompatImageView mLeftImage;
    private AppCompatTextView mName;

    public ContactCellViewHolder(LayoutInflater inflater, ViewGroup parent) {
        super(inflater.inflate(R.layout.contact_cell, parent, false));
        View v = itemView;
        mBottomLine = v.findViewById(R.id.bottom_line);
        mLeftImage = (AppCompatImageView) v.findViewById(R.id.left_image);
        mName = (AppCompatTextView) v.findViewById(R.id.name);
    }

    public void bind(ContactCellData contactCell) {
        mContactCellData = contactCell;
        mName.setText(mContactCellData.getName());
        String imageName = mContactCellData.getLeftImage();
        if (imageName != null) {
            int leftImageResId = itemView.getResources().getIdentifier(imageName, "drawable", "org.lianxianghui.weixindemo");
            if (leftImageResId != 0)
                mLeftImage.setImageResource(leftImageResId);
        }
        boolean clickable = mContactCellData.getClickable();
        if (clickable) {
            itemView.setEnabled(true);
            itemView.setOnClickListener(this);
        } else {
            itemView.setEnabled(false);
            itemView.setOnClickListener(null);
        }
    }

    @Override
    public void onClick(View view) {

    }



}

class ContactCellData {
    private String mCellId;
    private boolean mClickable;
    private String mName;
    private String mLeftImage;

    public String getCellId() {
        return mCellId;
    }

    public void setCellId(String cellId) {
        mCellId = cellId;
    }
    public boolean getClickable() {
        return mClickable;
    }

    public void setClickable(boolean clickable) {
        mClickable = clickable;
    }
    public String getName() {
        return mName;
    }

    public void setName(String name) {
        mName = name;
    }
    public String getLeftImage() {
        return mLeftImage;
    }

    public void setLeftImage(String leftImage) {
        mLeftImage = leftImage;
    }
}
