package org.lianxianghui.weixindemo.contacts.contacts;

import androidx.recyclerview.widget.RecyclerView;
import android.widget.Space;
import androidx.appcompat.widget.AppCompatTextView;
import android.content.Intent;
import androidx.appcompat.widget.AppCompatButton;
import androidx.core.graphics.drawable.RoundedBitmapDrawableFactory;
import androidx.appcompat.widget.AppCompatImageView;
import android.os.Bundle;
import org.lianxianghui.weixindemo.R;
import androidx.core.graphics.drawable.RoundedBitmapDrawable;
import android.graphics.Bitmap;
import android.view.KeyEvent;
import java.util.List;
import java.util.ArrayList;
import androidx.recyclerview.widget.LinearLayoutManager;
import android.view.LayoutInflater;
import android.graphics.BitmapFactory;
import android.view.View;
import android.widget.TextView;
import androidx.constraintlayout.widget.ConstraintLayout;
import android.view.ViewGroup;
import androidx.fragment.app.Fragment;

/**
* Generated by Sketch2Code
* Created by lianxianghui on 21-08-6.
*/

public class ContactsFragment extends Fragment {
    private static final String TAG = "ContactsFragment";
    private ConstraintLayout mContentView;
    private RecyclerView mListView;
    private ConstraintLayout mCustomNavigationBar;
    private View mBottomLine;
    private ConstraintLayout mRightButtonContainer;
    private AppCompatButton mRightButton;
    private AppCompatImageView mImage;
    private Space mPointForCenteryOfImage;
    private Space mPointForCenterxOfRightButton;
    private Space mPointForCenterxOfImage;
    private Space mPointForCenteryOfRightButton;
    private AppCompatTextView mTitle;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View v = inflater.inflate(R.layout.contacts_fragment, container, false);
 
        mContentView = (ConstraintLayout) v.findViewById(R.id.content_view);
        mListView = (RecyclerView) v.findViewById(R.id.list_view);
        mListView.setLayoutManager(new LinearLayoutManager(getActivity()));
        updateListView();
        mCustomNavigationBar = (ConstraintLayout) v.findViewById(R.id.custom_navigation_bar);
        mBottomLine = v.findViewById(R.id.bottom_line);
        mRightButtonContainer = (ConstraintLayout) v.findViewById(R.id.right_button_container);
        mRightButton = (AppCompatButton) v.findViewById(R.id.right_button);
        mRightButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {

            }
        });
        mImage = (AppCompatImageView) v.findViewById(R.id.image);
        mPointForCenteryOfImage = (Space) v.findViewById(R.id.point_for_centery_of_image);
        mPointForCenterxOfRightButton = (Space) v.findViewById(R.id.point_for_centerx_of_right_button);
        mPointForCenterxOfImage = (Space) v.findViewById(R.id.point_for_centerx_of_image);
        mPointForCenteryOfRightButton = (Space) v.findViewById(R.id.point_for_centery_of_right_button);
        mTitle = (AppCompatTextView) v.findViewById(R.id.title);
        return v;
    }

    private ListViewAdapter mListViewAdapter;
    private void updateListView() {
        List<Object> dataList  = getListViewDataList();
        mListViewAdapter = new ListViewAdapter(dataList);
        mListView.setAdapter(mListViewAdapter);
    }

    private List<Object> getListViewDataList() {
        ArrayList<Object> list = new ArrayList<Object>();

        ContactCellData cellData0 = new ContactCellData();
        cellData0.setCellId("0");
        cellData0.setClickable(true);
        cellData0.setName("新的朋友");
        cellData0.setLeftImage("contacts_contact_cell_left_image");
        list.add(cellData0);

        ContactCellData cellData1 = new ContactCellData();
        cellData1.setCellId("1");
        cellData1.setClickable(true);
        cellData1.setName("群聊");
        cellData1.setLeftImage("contacts_contact_cell_left_image_9");
        list.add(cellData1);

        ContactCellData cellData2 = new ContactCellData();
        cellData2.setCellId("2");
        cellData2.setClickable(true);
        cellData2.setName("标签");
        cellData2.setLeftImage("contacts_contact_cell_left_image_8");
        list.add(cellData2);

        ContactCellData cellData3 = new ContactCellData();
        cellData3.setCellId("3");
        cellData3.setClickable(true);
        cellData3.setName("公众号");
        cellData3.setLeftImage("contacts_contact_cell_left_image_7");
        list.add(cellData3);

        ContactsIndexCellData cellData4 = new ContactsIndexCellData();
        cellData4.setLabel("A");
        cellData4.setCellId("0");
        cellData4.setClickable(true);
        list.add(cellData4);

        ContactCellData cellData5 = new ContactCellData();
        cellData5.setCellId("4");
        cellData5.setClickable(true);
        cellData5.setName("阿丁");
        cellData5.setLeftImage("contacts_contact_cell_left_image_6");
        list.add(cellData5);

        ContactCellData cellData6 = new ContactCellData();
        cellData6.setCellId("5");
        cellData6.setClickable(true);
        cellData6.setName("阿连");
        cellData6.setLeftImage("contacts_contact_cell_left_image_5");
        list.add(cellData6);

        ContactCellData cellData7 = new ContactCellData();
        cellData7.setCellId("6");
        cellData7.setClickable(true);
        cellData7.setName("阿明");
        cellData7.setLeftImage("contacts_contact_cell_left_image_4");
        list.add(cellData7);

        ContactCellData cellData8 = new ContactCellData();
        cellData8.setCellId("7");
        cellData8.setClickable(true);
        cellData8.setName("阿连球");
        cellData8.setLeftImage("contacts_contact_cell_left_image_3");
        list.add(cellData8);

        ContactsIndexCellData cellData9 = new ContactsIndexCellData();
        cellData9.setLabel("S");
        cellData9.setCellId("1");
        cellData9.setClickable(true);
        list.add(cellData9);

        ContactCellData cellData10 = new ContactCellData();
        cellData10.setCellId("8");
        cellData10.setClickable(true);
        cellData10.setName("司马缸砸缸");
        cellData10.setLeftImage("contacts_contact_cell_left_image_2");
        list.add(cellData10);

        ContactCellData cellData11 = new ContactCellData();
        cellData11.setCellId("9");
        cellData11.setClickable(true);
        cellData11.setName("三趾树懒");
        cellData11.setLeftImage("contacts_contact_cell_left_image_1");
        list.add(cellData11);

        return list;
    }

    private class ListViewAdapter extends RecyclerView.Adapter<RecyclerView.ViewHolder> {
        private static final int ITEM_TYPE_CONTACTCELL = 0;
        private static final int ITEM_TYPE_CONTACTSINDEXCELL = 1;

        private List<Object> mDataList;

        public ListViewAdapter(List<Object> dataList) {
            mDataList = dataList;
        }

        @Override
        public RecyclerView.ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
            LayoutInflater layoutInflater = LayoutInflater.from(getActivity());
            if (viewType == ITEM_TYPE_CONTACTCELL) 
                return new ContactCellViewHolder(layoutInflater, parent);
            else if (viewType == ITEM_TYPE_CONTACTSINDEXCELL) 
                return new ContactsIndexCellViewHolder(layoutInflater, parent);
            else 
                return null;
        }

        @Override
        public void onBindViewHolder(RecyclerView.ViewHolder holder, int position) {
            Object data = mDataList.get(position);
            if (holder instanceof ContactCellViewHolder)
                ((ContactCellViewHolder) holder).bind((ContactCellData)data);
            else if (holder instanceof ContactsIndexCellViewHolder)
                ((ContactsIndexCellViewHolder) holder).bind((ContactsIndexCellData)data);
        }

        @Override
        public int getItemViewType(int position) {
            Object data = mDataList.get(position);
            if (data instanceof ContactCellData)
                return ITEM_TYPE_CONTACTCELL;
            else if (data instanceof ContactsIndexCellData)
                return ITEM_TYPE_CONTACTSINDEXCELL;
            else
                return -1;
        }

        @Override
        public int getItemCount() {
            return mDataList.size();
        }
    }



}




