package org.lianxianghui.weixindemo.contacts.contacts;

import androidx.core.graphics.drawable.RoundedBitmapDrawable;
import android.widget.Space;
import androidx.fragment.app.Fragment;
import android.view.LayoutInflater;
import android.widget.TextView;
import androidx.recyclerview.widget.LinearLayoutManager;
import android.view.ViewGroup;
import java.util.List;
import android.view.View;
import androidx.constraintlayout.widget.ConstraintLayout;
import android.graphics.BitmapFactory;
import org.lianxianghui.weixindemo.R;
import androidx.appcompat.widget.AppCompatTextView;
import androidx.core.graphics.drawable.RoundedBitmapDrawableFactory;
import java.util.ArrayList;
import androidx.appcompat.widget.AppCompatImageView;
import android.view.KeyEvent;
import android.graphics.Bitmap;
import androidx.appcompat.widget.AppCompatButton;
import android.content.Intent;
import androidx.recyclerview.widget.RecyclerView;
import android.os.Bundle;

/**
* Generated by Sketch2Code
* Created by lianxianghui on 21-08-18.
*/

public class ContactsFragment extends Fragment {
    private static final String TAG = "ContactsFragment";
    private ConstraintLayout contentView;
    private RecyclerView listView;
    private ConstraintLayout customNavigationBar;
    private View bottomLine;
    private ConstraintLayout rightButtonContainer;
    private AppCompatButton rightButton;
    private AppCompatImageView image;
    private Space pointForCenteryOfImage;
    private Space pointForCenterxOfRightButton;
    private Space pointForCenterxOfImage;
    private Space pointForCenteryOfRightButton;
    private AppCompatTextView title;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View v = inflater.inflate(R.layout.contacts_fragment, container, false);
 
        contentView = (ConstraintLayout) v.findViewById(R.id.content_view);
        listView = (RecyclerView) v.findViewById(R.id.list_view);
        listView.setLayoutManager(new LinearLayoutManager(getActivity()));
        updateListView();
        customNavigationBar = (ConstraintLayout) v.findViewById(R.id.custom_navigation_bar);
        bottomLine = v.findViewById(R.id.bottom_line);
        rightButtonContainer = (ConstraintLayout) v.findViewById(R.id.right_button_container);
        rightButton = (AppCompatButton) v.findViewById(R.id.right_button);
        rightButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {

            }
        });
        image = (AppCompatImageView) v.findViewById(R.id.image);
        pointForCenteryOfImage = (Space) v.findViewById(R.id.point_for_centery_of_image);
        pointForCenterxOfRightButton = (Space) v.findViewById(R.id.point_for_centerx_of_right_button);
        pointForCenterxOfImage = (Space) v.findViewById(R.id.point_for_centerx_of_image);
        pointForCenteryOfRightButton = (Space) v.findViewById(R.id.point_for_centery_of_right_button);
        title = (AppCompatTextView) v.findViewById(R.id.title);
        return v;
    }

    private ListViewAdapter listViewAdapter;
    private void updateListView() {
        List<Object> dataList  = getListViewDataList();
        listViewAdapter = new ListViewAdapter(dataList);
        listView.setAdapter(listViewAdapter);
    }

    private List<Object> getListViewDataList() {
        ArrayList<Object> list = new ArrayList<Object>();

        ContactCellData cellData0 = new ContactCellData();
        cellData0.setCellId("0");
        cellData0.setClickable(true);
        cellData0.setName("新的朋友");
        cellData0.setLeftImage("contacts_contact_cell_left_image");
        list.add(cellData0);

        ContactCellData cellData1 = new ContactCellData();
        cellData1.setCellId("1");
        cellData1.setClickable(true);
        cellData1.setName("群聊");
        cellData1.setLeftImage("contacts_contact_cell_left_image_9");
        list.add(cellData1);

        ContactCellData cellData2 = new ContactCellData();
        cellData2.setCellId("2");
        cellData2.setClickable(true);
        cellData2.setName("标签");
        cellData2.setLeftImage("contacts_contact_cell_left_image_8");
        list.add(cellData2);

        ContactCellData cellData3 = new ContactCellData();
        cellData3.setCellId("3");
        cellData3.setClickable(true);
        cellData3.setName("公众号");
        cellData3.setLeftImage("contacts_contact_cell_left_image_7");
        list.add(cellData3);

        ContactsIndexCellData cellData4 = new ContactsIndexCellData();
        cellData4.setLabel("A");
        cellData4.setCellId("0");
        cellData4.setClickable(true);
        list.add(cellData4);

        ContactCellData cellData5 = new ContactCellData();
        cellData5.setCellId("4");
        cellData5.setClickable(true);
        cellData5.setName("阿丁");
        cellData5.setLeftImage("contacts_contact_cell_left_image_6");
        list.add(cellData5);

        ContactCellData cellData6 = new ContactCellData();
        cellData6.setCellId("5");
        cellData6.setClickable(true);
        cellData6.setName("阿连");
        cellData6.setLeftImage("contacts_contact_cell_left_image_5");
        list.add(cellData6);

        ContactCellData cellData7 = new ContactCellData();
        cellData7.setCellId("6");
        cellData7.setClickable(true);
        cellData7.setName("阿明");
        cellData7.setLeftImage("contacts_contact_cell_left_image_4");
        list.add(cellData7);

        ContactCellData cellData8 = new ContactCellData();
        cellData8.setCellId("7");
        cellData8.setClickable(true);
        cellData8.setName("阿连球");
        cellData8.setLeftImage("contacts_contact_cell_left_image_3");
        list.add(cellData8);

        ContactsIndexCellData cellData9 = new ContactsIndexCellData();
        cellData9.setLabel("S");
        cellData9.setCellId("1");
        cellData9.setClickable(true);
        list.add(cellData9);

        ContactCellData cellData10 = new ContactCellData();
        cellData10.setCellId("8");
        cellData10.setClickable(true);
        cellData10.setName("司马缸砸缸");
        cellData10.setLeftImage("contacts_contact_cell_left_image_2");
        list.add(cellData10);

        ContactCellData cellData11 = new ContactCellData();
        cellData11.setCellId("9");
        cellData11.setClickable(true);
        cellData11.setName("三趾树懒");
        cellData11.setLeftImage("contacts_contact_cell_left_image_1");
        list.add(cellData11);

        return list;
    }

    private class ListViewAdapter extends RecyclerView.Adapter<RecyclerView.ViewHolder> {
        private static final int ITEM_TYPE_CONTACTCELL = 0;
        private static final int ITEM_TYPE_CONTACTSINDEXCELL = 1;

        private List<Object> dataList;

        public ListViewAdapter(List<Object> dataList) {
            this.dataList = dataList;
        }

        @Override
        public RecyclerView.ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
            LayoutInflater layoutInflater = LayoutInflater.from(getActivity());
            if (viewType == ITEM_TYPE_CONTACTCELL)  {
                ContactCellViewHolder viewHolder = new ContactCellViewHolder(layoutInflater, parent);
                return viewHolder;
            }
            else if (viewType == ITEM_TYPE_CONTACTSINDEXCELL)  {
                ContactsIndexCellViewHolder viewHolder = new ContactsIndexCellViewHolder(layoutInflater, parent);
                return viewHolder;
            }
            else 
                return null;
        }

        @Override
        public void onBindViewHolder(RecyclerView.ViewHolder holder, int position) {
            Object data = dataList.get(position);
            if (holder instanceof ContactCellViewHolder) {
		        ContactCellViewHolder viewHolder = (ContactCellViewHolder)holder;
		        ContactCellData contactCellData = (ContactCellData)data;
                viewHolder.bind(contactCellData);
                boolean clickable = contactCellData.getClickable();
                if (clickable) {
                    viewHolder.itemView.setOnClickListener(new View.OnClickListener() {
                        @Override
                        public void onClick(View view) {

                        }
                    });
                } else {
                    viewHolder.itemView.setOnClickListener(null);
                }
            }
            else if (holder instanceof ContactsIndexCellViewHolder) {
		        ContactsIndexCellViewHolder viewHolder = (ContactsIndexCellViewHolder)holder;
		        ContactsIndexCellData contactsIndexCellData = (ContactsIndexCellData)data;
                viewHolder.bind(contactsIndexCellData);
                boolean clickable = contactsIndexCellData.getClickable();
                if (clickable) {
                    viewHolder.itemView.setOnClickListener(new View.OnClickListener() {
                        @Override
                        public void onClick(View view) {

                        }
                    });
                } else {
                    viewHolder.itemView.setOnClickListener(null);
                }
            }
        }

        @Override
        public int getItemViewType(int position) {
            Object data = dataList.get(position);
            if (data instanceof ContactCellData)
                return ITEM_TYPE_CONTACTCELL;
            else if (data instanceof ContactsIndexCellData)
                return ITEM_TYPE_CONTACTSINDEXCELL;
            else
                return -1;
        }

        @Override
        public int getItemCount() {
            return dataList.size();
        }

    }



}




