package org.lianxianghui.weixindemo.contacts.contacts;

import androidx.appcompat.widget.AppCompatTextView;
import org.lianxianghui.weixindemo.R;
import android.graphics.BitmapFactory;
import androidx.core.graphics.drawable.RoundedBitmapDrawableFactory;
import android.view.ViewGroup;
import androidx.recyclerview.widget.RecyclerView;
import android.view.View;
import android.content.Intent;
import androidx.appcompat.widget.AppCompatImageView;
import android.view.KeyEvent;
import android.graphics.Bitmap;
import android.widget.TextView;
import androidx.constraintlayout.widget.ConstraintLayout;
import android.view.LayoutInflater;
import androidx.core.graphics.drawable.RoundedBitmapDrawable;

/**
* Generated by Sketch2Code
* Created by lianxianghui on 21-08-18.
*/

public class ContactCellViewHolder extends RecyclerView.ViewHolder {
    private ContactCellData contactCellData;

    public final View bottomLine;
    public final AppCompatImageView leftImage;
    public final AppCompatTextView name;

    public ContactCellViewHolder(LayoutInflater inflater, ViewGroup parent) {
        super(inflater.inflate(R.layout.contact_cell, parent, false));
        View v = itemView;
        bottomLine = v.findViewById(R.id.bottom_line);
        leftImage = (AppCompatImageView) v.findViewById(R.id.left_image);
        name = (AppCompatTextView) v.findViewById(R.id.name);
    }

    public void bind(ContactCellData contactCellData) {
        this.contactCellData = contactCellData;
        name.setText(contactCellData.getName());
        String imageName = contactCellData.getLeftImage();
        if (imageName != null) {
            int leftImageResId = itemView.getResources().getIdentifier(imageName, "drawable", "org.lianxianghui.weixindemo");
            if (leftImageResId != 0)
                leftImage.setImageResource(leftImageResId);
        }
        boolean clickable = contactCellData.getClickable();
        if (clickable) {
            itemView.setEnabled(true);
        } else {
            itemView.setEnabled(false);
        }
    }

    public ContactCellData getContactCellData() {
        return contactCellData;
    }



}

class ContactCellData {
    private String cellId;
    private boolean clickable;
    private String name;
    private String leftImage;

    public String getCellId() {
        return cellId;
    }
    public void setCellId(String cellId) {
        this.cellId = cellId;
    }

    public boolean getClickable() {
        return clickable;
    }
    public void setClickable(boolean clickable) {
        this.clickable = clickable;
    }

    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }

    public String getLeftImage() {
        return leftImage;
    }
    public void setLeftImage(String leftImage) {
        this.leftImage = leftImage;
    }

}
