package org.lianxianghui.weixindemo.me.me;

import androidx.recyclerview.widget.RecyclerView;
import android.widget.Space;
import androidx.appcompat.widget.AppCompatTextView;
import android.content.Intent;
import androidx.core.graphics.drawable.RoundedBitmapDrawableFactory;
import androidx.appcompat.widget.AppCompatImageView;
import org.lianxianghui.weixindemo.R;
import androidx.core.graphics.drawable.RoundedBitmapDrawable;
import android.graphics.Bitmap;
import android.view.KeyEvent;
import android.view.LayoutInflater;
import android.graphics.BitmapFactory;
import android.view.View;
import android.widget.TextView;
import androidx.constraintlayout.widget.ConstraintLayout;
import android.view.ViewGroup;

/**
* Generated by Sketch2Code
* Created by lianxianghui on 21-08-6.
*/

public class MeMyInfoCellViewHolder extends RecyclerView.ViewHolder implements View.OnClickListener {
    private MeMyInfoCellData mMeMyInfoCellData;

    private View mBottomLine;
    private AppCompatImageView mRightIcon;
    private AppCompatTextView mLabel;
    private AppCompatTextView mName;
    private AppCompatImageView mRightImage;
    private AppCompatImageView mHeadImage;
    private Space mPointForBottomOfNameToTopOfRightImage;

    public MeMyInfoCellViewHolder(LayoutInflater inflater, ViewGroup parent) {
        super(inflater.inflate(R.layout.me_my_info_cell, parent, false));
        View v = itemView;
        mBottomLine = v.findViewById(R.id.bottom_line);
        mRightIcon = (AppCompatImageView) v.findViewById(R.id.right_icon);
        mLabel = (AppCompatTextView) v.findViewById(R.id.label);
        mName = (AppCompatTextView) v.findViewById(R.id.name);
        mRightImage = (AppCompatImageView) v.findViewById(R.id.right_image);
        mHeadImage = (AppCompatImageView) v.findViewById(R.id.head_image);
        mPointForBottomOfNameToTopOfRightImage = (Space) v.findViewById(R.id.point_for_bottom_of_name_to_top_of_right_image);
    }

    public void bind(MeMyInfoCellData meMyInfoCell) {
        mMeMyInfoCellData = meMyInfoCell;
        mLabel.setText(mMeMyInfoCellData.getLabel());
        mName.setText(mMeMyInfoCellData.getName());
        String imageName = mMeMyInfoCellData.getRightIcon();
        if (imageName != null) {
            int rightIconResId = itemView.getResources().getIdentifier(imageName, "drawable", "org.lianxianghui.weixindemo");
            if (rightIconResId != 0)
                mRightIcon.setImageResource(rightIconResId);
        }
        imageName = mMeMyInfoCellData.getRightImage();
        if (imageName != null) {
            int rightImageResId = itemView.getResources().getIdentifier(imageName, "drawable", "org.lianxianghui.weixindemo");
            if (rightImageResId != 0)
                mRightImage.setImageResource(rightImageResId);
        }
        imageName = mMeMyInfoCellData.getHeadImage();
        if (imageName != null) {
            int headImageResId = itemView.getResources().getIdentifier(imageName, "drawable", "org.lianxianghui.weixindemo");
            if (headImageResId != 0)
                mHeadImage.setImageResource(headImageResId);
        }
        boolean clickable = mMeMyInfoCellData.getClickable();
        if (clickable) {
            itemView.setEnabled(true);
            itemView.setOnClickListener(this);
        } else {
            itemView.setEnabled(false);
            itemView.setOnClickListener(null);
        }
    }

    @Override
    public void onClick(View view) {

    }






}

class MeMyInfoCellData {
    private String mCellId;
    private String mHeadImage;
    private String mRightIcon;
    private String mLabel;
    private boolean mClickable;
    private String mName;
    private String mRightImage;

    public String getCellId() {
        return mCellId;
    }

    public void setCellId(String cellId) {
        mCellId = cellId;
    }
    public String getHeadImage() {
        return mHeadImage;
    }

    public void setHeadImage(String headImage) {
        mHeadImage = headImage;
    }
    public String getRightIcon() {
        return mRightIcon;
    }

    public void setRightIcon(String rightIcon) {
        mRightIcon = rightIcon;
    }
    public String getLabel() {
        return mLabel;
    }

    public void setLabel(String label) {
        mLabel = label;
    }
    public boolean getClickable() {
        return mClickable;
    }

    public void setClickable(boolean clickable) {
        mClickable = clickable;
    }
    public String getName() {
        return mName;
    }

    public void setName(String name) {
        mName = name;
    }
    public String getRightImage() {
        return mRightImage;
    }

    public void setRightImage(String rightImage) {
        mRightImage = rightImage;
    }
}
