package org.lianxianghui.weixindemo.me.me;

import androidx.recyclerview.widget.RecyclerView;
import androidx.appcompat.widget.AppCompatTextView;
import android.content.Intent;
import androidx.core.graphics.drawable.RoundedBitmapDrawableFactory;
import androidx.appcompat.widget.AppCompatImageView;
import org.lianxianghui.weixindemo.R;
import androidx.core.graphics.drawable.RoundedBitmapDrawable;
import android.graphics.Bitmap;
import android.view.KeyEvent;
import android.view.LayoutInflater;
import android.graphics.BitmapFactory;
import android.view.View;
import android.widget.TextView;
import androidx.constraintlayout.widget.ConstraintLayout;
import android.view.ViewGroup;

/**
* Generated by Sketch2Code
* Created by lianxianghui on 21-08-6.
*/

public class MeWalletCellViewHolder extends RecyclerView.ViewHolder implements View.OnClickListener {
    private MeWalletCellData mMeWalletCellData;

    private View mBottomLine;
    private AppCompatImageView mLeftImage;
    private AppCompatTextView mName;
    private AppCompatImageView mRightIcon;

    public MeWalletCellViewHolder(LayoutInflater inflater, ViewGroup parent) {
        super(inflater.inflate(R.layout.me_wallet_cell, parent, false));
        View v = itemView;
        mBottomLine = v.findViewById(R.id.bottom_line);
        mLeftImage = (AppCompatImageView) v.findViewById(R.id.left_image);
        mName = (AppCompatTextView) v.findViewById(R.id.name);
        mRightIcon = (AppCompatImageView) v.findViewById(R.id.right_icon);
    }

    public void bind(MeWalletCellData meWalletCell) {
        mMeWalletCellData = meWalletCell;
        mName.setText(mMeWalletCellData.getName());
        String imageName = mMeWalletCellData.getLeftImage();
        if (imageName != null) {
            int leftImageResId = itemView.getResources().getIdentifier(imageName, "drawable", "org.lianxianghui.weixindemo");
            if (leftImageResId != 0)
                mLeftImage.setImageResource(leftImageResId);
        }
        imageName = mMeWalletCellData.getRightIcon();
        if (imageName != null) {
            int rightIconResId = itemView.getResources().getIdentifier(imageName, "drawable", "org.lianxianghui.weixindemo");
            if (rightIconResId != 0)
                mRightIcon.setImageResource(rightIconResId);
        }
        boolean clickable = mMeWalletCellData.getClickable();
        if (clickable) {
            itemView.setEnabled(true);
            itemView.setOnClickListener(this);
        } else {
            itemView.setEnabled(false);
            itemView.setOnClickListener(null);
        }
    }

    @Override
    public void onClick(View view) {

    }




}

class MeWalletCellData {
    private String mLeftImage;
    private String mCellId;
    private boolean mClickable;
    private String mName;
    private String mRightIcon;

    public String getLeftImage() {
        return mLeftImage;
    }

    public void setLeftImage(String leftImage) {
        mLeftImage = leftImage;
    }
    public String getCellId() {
        return mCellId;
    }

    public void setCellId(String cellId) {
        mCellId = cellId;
    }
    public boolean getClickable() {
        return mClickable;
    }

    public void setClickable(boolean clickable) {
        mClickable = clickable;
    }
    public String getName() {
        return mName;
    }

    public void setName(String name) {
        mName = name;
    }
    public String getRightIcon() {
        return mRightIcon;
    }

    public void setRightIcon(String rightIcon) {
        mRightIcon = rightIcon;
    }
}
