// LXHMainTabBarPageViewModel.h
// WeiXinDemo
//
//  Created by lianxianghui on 21-08-18
//  Generated by Sketch2Code
//  Copyright © 2021年 lianxianghui. All rights reserved.

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

@interface LXHMainTabBarPageViewModel : NSObject

- (id)meViewModel;
- (id)findViewModel;
- (id)contactsViewModel;
- (id)conversationListViewModel;
@end

NS_ASSUME_NONNULL_END
