// LXHMainTabBarPageViewController.m
// WeiXinDemo
//
//  Created by lianxianghui on 21-08-18
//  Generated by Sketch2Code
//  Copyright © 2021年 lianxianghui. All rights reserved.

#import "LXHMainTabBarPageViewController.h"
#import "LXHMainTabBarPageViewModel.h"
#import "LXHMeViewController.h"
#import "LXHFindViewController.h"
#import "LXHContactsViewController.h"
#import "LXHConversationListViewController.h"


#define UIColorFromRGBA(rgbaValue) \
[UIColor colorWithRed:((rgbaValue & 0xFF000000) >> 24)/255.0 \
        green:((rgbaValue & 0x00FF0000) >>  16)/255.0 \
        blue:((rgbaValue & 0x0000FF00) >>  8)/255.0 \
        alpha:(rgbaValue & 0x000000FF)/255.0]

@interface LXHMainTabBarPageViewController()
@property (nonatomic) LXHMainTabBarPageViewModel *viewModel;
@end

@implementation LXHMainTabBarPageViewController
- (instancetype)initWithViewModel:(id)viewModel {
    self.viewModel = viewModel;
    self = [super init];
    if (self) {
    }
    return self;
}

- (void)viewDidLoad {
    [super viewDidLoad];
    self.view.backgroundColor = UIColorFromRGBA(0xFFFFFFFF);
    [self.navigationController setNavigationBarHidden:YES animated:NO];
    self.automaticallyAdjustsScrollViewInsets = NO;
    self.tabBar.barTintColor = UIColorFromRGBA(0xFAFAFAE6);
    self.tabBar.tintColor = UIColorFromRGBA(0x1AAD19FF);
    self.tabBar.unselectedItemTintColor = UIColorFromRGBA(0x929292FF);

    UITabBarItem *item = nil;
    UIImage *itemImage = nil;
    UIImage *itemSelectedImage = nil;
    UIViewController *viewController = nil;
    id viewModel = nil;
    UINavigationController *navigationController = nil;

    viewModel = [self.viewModel conversationListViewModel];
    viewController = [[LXHConversationListViewController alloc] initWithViewModel:viewModel];
    navigationController = [[UINavigationController alloc] initWithRootViewController:viewController];
    id swipeRecognizer = [[UISwipeGestureRecognizer alloc] initWithTarget:self action:@selector(swipeView:)];//default direction is UISwipeGestureRecognizerDirectionRight
    [viewController.view addGestureRecognizer:swipeRecognizer];
    itemImage = [UIImage imageNamed:@"weixin_main_tab_bar_page_view_item1_inner_icon"];
    itemSelectedImage = [UIImage imageNamed:@"weixin_main_tab_bar_page_view_item1_inner_selected_icon"];
    item = [[UITabBarItem alloc] initWithTitle:NSLocalizedString(@"微信", nil) image:itemImage selectedImage:itemSelectedImage];
    navigationController.tabBarItem = item;
    [self addChildViewController:navigationController];

    viewModel = [self.viewModel contactsViewModel];
    viewController = [[LXHContactsViewController alloc] initWithViewModel:viewModel];
    navigationController = [[UINavigationController alloc] initWithRootViewController:viewController];
    itemImage = [UIImage imageNamed:@"weixin_main_tab_bar_page_view_item2_inner_icon"];
    itemSelectedImage = [UIImage imageNamed:@"weixin_main_tab_bar_page_view_item2_inner_selected_icon"];
    item = [[UITabBarItem alloc] initWithTitle:NSLocalizedString(@"通讯录", nil) image:itemImage selectedImage:itemSelectedImage];
    navigationController.tabBarItem = item;
    [self addChildViewController:navigationController];

    viewModel = [self.viewModel findViewModel];
    viewController = [[LXHFindViewController alloc] initWithViewModel:viewModel];
    navigationController = [[UINavigationController alloc] initWithRootViewController:viewController];
    itemImage = [UIImage imageNamed:@"weixin_main_tab_bar_page_view_item3_inner_icon"];
    itemSelectedImage = [UIImage imageNamed:@"weixin_main_tab_bar_page_view_item3_inner_selected_icon"];
    item = [[UITabBarItem alloc] initWithTitle:NSLocalizedString(@"发现", nil) image:itemImage selectedImage:itemSelectedImage];
    navigationController.tabBarItem = item;
    [self addChildViewController:navigationController];

    viewModel = [self.viewModel meViewModel];
    viewController = [[LXHMeViewController alloc] initWithViewModel:viewModel];
    navigationController = [[UINavigationController alloc] initWithRootViewController:viewController];
    itemImage = [UIImage imageNamed:@"weixin_main_tab_bar_page_view_item4_inner_icon"];
    itemSelectedImage = [UIImage imageNamed:@"weixin_main_tab_bar_page_view_item4_inner_selected_icon"];
    item = [[UITabBarItem alloc] initWithTitle:NSLocalizedString(@"我", nil) image:itemImage selectedImage:itemSelectedImage];
    navigationController.tabBarItem = item;
    [self addChildViewController:navigationController];

    self.tabBar.translucent = NO;
}

- (void)swipeView:(id)sender {
    [self.navigationController popViewControllerAnimated:YES];
}

- (UIStatusBarStyle)preferredStatusBarStyle {
    return UIStatusBarStyleDefault;
}
@end
