// LXHMainTabBarPageViewModel.m
// WeiXinDemo
//
//  Created by lianxianghui on 21-08-18
//  Generated by Sketch2Code
//  Copyright © 2021年 lianxianghui. All rights reserved.


#import "LXHMainTabBarPageViewModel.h"
#import "LXHMeViewModel.h"
#import "LXHFindViewModel.h"
#import "LXHContactsViewModel.h"
#import "LXHConversationListViewModel.h"

@interface LXHMainTabBarPageViewModel ()
@end

@implementation LXHMainTabBarPageViewModel

- (instancetype)init {
    self = [super init];
    if (self) {
    }
    return self;
}

- (id)meViewModel {
    id viewModel = [[LXHMeViewModel alloc] init];
    return viewModel;
}
- (id)findViewModel {
    id viewModel = [[LXHFindViewModel alloc] init];
    return viewModel;
}
- (id)contactsViewModel {
    id viewModel = [[LXHContactsViewModel alloc] init];
    return viewModel;
}
- (id)conversationListViewModel {
    id viewModel = [[LXHConversationListViewModel alloc] init];
    return viewModel;
}

@end
