// LXHMeCell.h
// WeiXinDemo
//
//  Created by lianxianghui on 21-08-9
//  Generated by Sketch2Code
//  Copyright © 2021年 lianxianghui. All rights reserved.

#import <UIKit/UIKit.h>

@interface LXHMeCell : UIView

@property (nonatomic) UIView *bottomLine;
@property (nonatomic) UIImageView *leftImage;
@property (nonatomic) UILabel *name;
@property (nonatomic) UIImageView *rightIcon;

@end
