// LXHMeMyInfoCell.h
// WeiXinDemo
//
//  Created by lianxianghui on 21-08-9
//  Generated by Sketch2Code
//  Copyright © 2021年 lianxianghui. All rights reserved.

#import <UIKit/UIKit.h>

@interface LXHMeMyInfoCell : UIView

@property (nonatomic) UIView *bottomLine;
@property (nonatomic) UIImageView *rightIcon;
@property (nonatomic) UILabel *label;
@property (nonatomic) UILabel *name;
@property (nonatomic) UIImageView *rightImage;
@property (nonatomic) UIImageView *headImage;

@end
