// LXHMeMyInfoCell.m
// WeiXinDemo
//
//  Created by lianxianghui on 21-08-9
//  Generated by Sketch2Code
//  Copyright © 2021年 lianxianghui. All rights reserved.


#import "LXHMeMyInfoCell.h"
#import "Masonry.h"

#define UIColorFromRGBA(rgbaValue) \
[UIColor colorWithRed:((rgbaValue & 0xFF000000) >> 24)/255.0 \
        green:((rgbaValue & 0x00FF0000) >>  16)/255.0 \
        blue:((rgbaValue & 0x0000FF00) >>  8)/255.0 \
        alpha:(rgbaValue & 0x000000FF)/255.0]

@interface LXHMeMyInfoCell()
@end

@implementation LXHMeMyInfoCell

- (instancetype)initWithFrame:(CGRect)frame {
    self = [super initWithFrame:frame];
    if (self) {
        self.backgroundColor = UIColorFromRGBA(0xFFFFFFFF);
        self.alpha = 1;
        [self addSubviews];
        [self makeConstraints];
    }
    return self;
}

- (void)addSubviews {
    [self addSubview:self.bottomLine];
    [self addSubview:self.rightIcon];
    [self addSubview:self.label];
    [self addSubview:self.name];
    [self addSubview:self.rightImage];
    [self addSubview:self.headImage];
}

- (void)makeConstraints {
    [self.bottomLine mas_makeConstraints:^(MASConstraintMaker *make) {
        make.right.equalTo(self.mas_right);
        make.bottom.equalTo(self.mas_bottom);
        make.left.equalTo(self.mas_left);
        make.height.mas_equalTo(0.5099999904632568);
    }];
    [self.rightIcon mas_makeConstraints:^(MASConstraintMaker *make) {
        make.right.equalTo(self.mas_right).offset(-15);
        make.centerY.equalTo(self.mas_centerY);
        make.width.mas_equalTo(8.020000457763672);
        make.height.mas_equalTo(13);
    }];
    [self.label mas_makeConstraints:^(MASConstraintMaker *make) {
        make.left.equalTo(self.name.mas_left);
        make.bottom.equalTo(self.headImage.mas_bottom).offset(-4.355000019073486);
    }];
    [self.name mas_makeConstraints:^(MASConstraintMaker *make) {
        make.height.mas_equalTo(23);
        make.left.equalTo(self.headImage.mas_right).offset(10.23929977416992);
        make.top.equalTo(self.rightImage.mas_top).offset(-14);
    }];
    [self.rightImage mas_makeConstraints:^(MASConstraintMaker *make) {
        make.centerY.equalTo(self.mas_centerY);
        make.right.equalTo(self.rightIcon.mas_right).offset(-18);
        make.width.mas_equalTo(18);
        make.height.mas_equalTo(18);
    }];
    [self.headImage mas_makeConstraints:^(MASConstraintMaker *make) {
        make.left.equalTo(self.mas_left).offset(10);
        make.centerY.equalTo(self.mas_centerY);
    }];
}

//Getters
- (UIView *)bottomLine {
    if (!_bottomLine) {
        _bottomLine = [[UIView alloc] init];
        _bottomLine.backgroundColor = UIColorFromRGBA(0xD8D8D8FF);
        _bottomLine.alpha = 1;
    }
    return _bottomLine;
}

- (UIImageView *)rightIcon {
    if (!_rightIcon) {
        _rightIcon = [[UIImageView alloc] init];
        _rightIcon.alpha = 1;
        _rightIcon.image = [UIImage imageNamed:@"me_me_my_info_cell_right_icon"];
    }
    return _rightIcon;
}

- (UILabel *)label {
    if (!_label) {
        _label = [[UILabel alloc] init];
        _label.backgroundColor = UIColorFromRGBA(0xFFFFFF00);
        _label.alpha = 1;

        _label.numberOfLines = 0;
        UIFont *font = [UIFont fontWithName:@"PingFangSC-Regular" size:12];
        if (!font) font = [UIFont systemFontOfSize:12];

        NSMutableDictionary *textAttributes = [NSMutableDictionary dictionary];
        [textAttributes setObject:UIColorFromRGBA(0x9E9E9EFF) forKey:NSForegroundColorAttributeName];
        [textAttributes setObject:font forKey:NSFontAttributeName];
        [textAttributes setObject:@(-0.534) forKey:NSKernAttributeName];
        NSAttributedString *text = [[NSAttributedString alloc] initWithString:NSLocalizedString(@"微信号：Sketch2Code", nil) attributes:textAttributes];
        _label.attributedText = text;
        _label.textAlignment = NSTextAlignmentNatural;
    }
    return _label;
}

- (UILabel *)name {
    if (!_name) {
        _name = [[UILabel alloc] init];
        _name.backgroundColor = UIColorFromRGBA(0xFFFFFF00);
        _name.alpha = 1;

        _name.numberOfLines = 0;
        UIFont *font = [UIFont fontWithName:@"PingFangSC-Regular" size:14];
        if (!font) font = [UIFont systemFontOfSize:14];

        NSMutableDictionary *textAttributes = [NSMutableDictionary dictionary];
        [textAttributes setObject:UIColorFromRGBA(0x1B1B1BFF) forKey:NSForegroundColorAttributeName];
        [textAttributes setObject:font forKey:NSFontAttributeName];
        [textAttributes setObject:@(-0.623) forKey:NSKernAttributeName];
        NSAttributedString *text = [[NSAttributedString alloc] initWithString:NSLocalizedString(@"Skech2Code", nil) attributes:textAttributes];
        _name.attributedText = text;
        _name.textAlignment = NSTextAlignmentNatural;
    }
    return _name;
}

- (UIImageView *)rightImage {
    if (!_rightImage) {
        _rightImage = [[UIImageView alloc] init];
        _rightImage.alpha = 1;
        _rightImage.image = [UIImage imageNamed:@"me_me_my_info_cell_right_image"];
    }
    return _rightImage;
}

- (UIImageView *)headImage {
    if (!_headImage) {
        _headImage = [[UIImageView alloc] init];
        _headImage.alpha = 1;
        _headImage.image = [UIImage imageNamed:@"me_me_my_info_cell_head_image"];
    }
    return _headImage;
}


@end

