// LXHMeViewModel.m
// WeiXinDemo
//
//  Created by lianxianghui on 21-08-9
//  Generated by Sketch2Code
//  Copyright © 2021年 lianxianghui. All rights reserved.


#import "LXHMeViewModel.h"

@interface LXHMeViewModel ()
@property (nonatomic) NSMutableArray *cellDataArrayForListView;
@end

@implementation LXHMeViewModel

- (instancetype)init {
    self = [super init];
    if (self) {
    }
    return self;
}

- (NSMutableArray *)cellDataArrayForListView {
    if (!_cellDataArrayForListView) {
        _cellDataArrayForListView = [NSMutableArray array];
        NSDictionary *dic = nil;
        dic = @{@"clickable":@"0", @"cellId":@"0", @"cellType":@"LXHMeGapCell"};
        [_cellDataArrayForListView addObject:dic];
        dic = @{@"cellId":@"0", @"cellType":@"LXHMeMyInfoCell", @"headImage":@"me_me_my_info_cell_head_image", @"rightIcon":@"me_me_my_info_cell_right_icon", @"label":@"微信号：Sketch2Code", @"clickable":@"1", @"name":@"Skech2Code", @"rightImage":@"me_me_my_info_cell_right_image"};
        [_cellDataArrayForListView addObject:dic];
        dic = @{@"clickable":@"1", @"cellId":@"1", @"cellType":@"LXHMeGapCell"};
        [_cellDataArrayForListView addObject:dic];
        dic = @{@"leftImage":@"me_me_wallet_cell_left_image", @"cellId":@"0", @"clickable":@"1", @"name":@"钱包", @"cellType":@"LXHMeWalletCell", @"rightIcon":@"me_me_wallet_cell_right_icon"};
        [_cellDataArrayForListView addObject:dic];
        dic = @{@"clickable":@"1", @"cellId":@"2", @"cellType":@"LXHMeGapCell"};
        [_cellDataArrayForListView addObject:dic];
        dic = @{@"leftImage":@"me_me_cell_left_image", @"cellId":@"0", @"clickable":@"1", @"name":@"收藏", @"cellType":@"LXHMeCell", @"rightIcon":@"me_me_cell_right_icon"};
        [_cellDataArrayForListView addObject:dic];
        dic = @{@"leftImage":@"me_me_cell_left_image_4", @"cellId":@"1", @"clickable":@"1", @"name":@"相册", @"cellType":@"LXHMeCell", @"rightIcon":@"me_me_cell_right_icon_4"};
        [_cellDataArrayForListView addObject:dic];
        dic = @{@"leftImage":@"me_me_cell_left_image_3", @"cellId":@"2", @"clickable":@"1", @"name":@"卡包", @"cellType":@"LXHMeCell", @"rightIcon":@"me_me_cell_right_icon_3"};
        [_cellDataArrayForListView addObject:dic];
        dic = @{@"leftImage":@"me_me_cell_left_image_2", @"cellId":@"3", @"clickable":@"1", @"name":@"表情", @"cellType":@"LXHMeCell", @"rightIcon":@"me_me_cell_right_icon_2"};
        [_cellDataArrayForListView addObject:dic];
        dic = @{@"clickable":@"1", @"cellId":@"3", @"cellType":@"LXHMeGapCell"};
        [_cellDataArrayForListView addObject:dic];
        dic = @{@"leftImage":@"me_me_cell_left_image_1", @"cellId":@"4", @"clickable":@"1", @"name":@"设置", @"cellType":@"LXHMeCell", @"rightIcon":@"me_me_cell_right_icon_1"};
        [_cellDataArrayForListView addObject:dic];
    }
    return _cellDataArrayForListView;
}


@end
