package org.lianxianghui.weixindemo.weixin.maintabbarpage;

import android.os.Bundle;
import androidx.fragment.app.Fragment;
import androidx.appcompat.app.AppCompatActivity;

import com.google.android.material.bottomnavigation.BottomNavigationView;
import android.view.MenuItem;
import androidx.viewpager.widget.ViewPager;
import androidx.fragment.app.FragmentPagerAdapter;
import androidx.annotation.NonNull;

import org.lianxianghui.weixindemo.R;

/**
* Generated by Sketch2Code
* Created by lianxianghui on 21-08-6.
*/

public class MainTabBarPageActivity extends AppCompatActivity {
    private static final String TAG = "MainTabBarPageActivity";

    private BottomNavigationView mNavigationView;
    private ViewPager mViewPager;

    private Fragment mItem1Fragment = new org.lianxianghui.weixindemo.weixin.conversationlist.ConversationListFragment();
    private Fragment mItem2Fragment = new org.lianxianghui.weixindemo.contacts.contacts.ContactsFragment();
    private Fragment mItem3Fragment = new org.lianxianghui.weixindemo.find.find.FindFragment();
    private Fragment mItem4Fragment = new org.lianxianghui.weixindemo.me.me.MeFragment();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.main_tab_bar_page_activity);

        mViewPager = findViewById(R.id.view_pager);
        mNavigationView = findViewById(R.id.nav_view);

        mViewPager.addOnPageChangeListener(new ViewPager.OnPageChangeListener() {
            @Override
            public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {

            }

            @Override
            public void onPageSelected(int position) {
                //页面滑动的时候，改变BottomNavigationView的Item高亮
                mNavigationView.getMenu().getItem(position).setChecked(true);
            }

            @Override
            public void onPageScrollStateChanged(int state) {

            }
        });

        mNavigationView.setOnNavigationItemSelectedListener(new BottomNavigationView.OnNavigationItemSelectedListener() {
            @Override
            public boolean onNavigationItemSelected(@NonNull MenuItem item) {
                //点击BottomNavigationView的Item项，切换ViewPager页面
                //menu/navigation.xml里加的android:orderInCategory属性就是下面item.getOrder()取的值
                mViewPager.setCurrentItem(item.getOrder());
                return true;
            }
        });

        mViewPager.setAdapter(new FragmentPagerAdapter(getSupportFragmentManager(), FragmentPagerAdapter.BEHAVIOR_RESUME_ONLY_CURRENT_FRAGMENT) {
            @Override
            public Fragment getItem(int position) {
                switch (position) {
                    case 0:
                        return mItem1Fragment;
                    case 1:
                        return mItem2Fragment;
                    case 2:
                        return mItem3Fragment;
                    case 3:
                        return mItem4Fragment;
                }
                return null;
            }

            @Override
            public int getCount() {
                return 4;
            }
        });
    }
}
