package org.lianxianghui.weixindemo.weixin.conversationlist;

import androidx.appcompat.widget.AppCompatTextView;
import org.lianxianghui.weixindemo.R;
import android.graphics.BitmapFactory;
import androidx.core.graphics.drawable.RoundedBitmapDrawableFactory;
import android.view.ViewGroup;
import androidx.recyclerview.widget.RecyclerView;
import android.view.View;
import android.content.Intent;
import androidx.appcompat.widget.AppCompatImageView;
import android.view.KeyEvent;
import android.graphics.Bitmap;
import android.widget.TextView;
import androidx.constraintlayout.widget.ConstraintLayout;
import android.view.LayoutInflater;
import androidx.core.graphics.drawable.RoundedBitmapDrawable;

/**
* Generated by Sketch2Code
* Created by lianxianghui on 21-08-6.
*/

public class ConversationListLoginStatusCellViewHolder extends RecyclerView.ViewHolder implements View.OnClickListener {
    private ConversationListLoginStatusCellData mConversationListLoginStatusCellData;

    private AppCompatImageView mStatusImage;
    private AppCompatTextView mStatusLabel;

    public ConversationListLoginStatusCellViewHolder(LayoutInflater inflater, ViewGroup parent) {
        super(inflater.inflate(R.layout.conversation_list_login_status_cell, parent, false));
        View v = itemView;
        mStatusImage = (AppCompatImageView) v.findViewById(R.id.status_image);
        mStatusLabel = (AppCompatTextView) v.findViewById(R.id.status_label);
        setStatusLabelMultipleStyles();
    }

    public void bind(ConversationListLoginStatusCellData conversationListLoginStatusCell) {
        mConversationListLoginStatusCellData = conversationListLoginStatusCell;
        mStatusLabel.setText(mConversationListLoginStatusCellData.getStatusLabel());
        String imageName = mConversationListLoginStatusCellData.getStatusImage();
        if (imageName != null) {
            int statusImageResId = itemView.getResources().getIdentifier(imageName, "drawable", "org.lianxianghui.weixindemo");
            if (statusImageResId != 0)
                mStatusImage.setImageResource(statusImageResId);
        }
        boolean clickable = mConversationListLoginStatusCellData.getClickable();
        if (clickable) {
            itemView.setEnabled(true);
            itemView.setOnClickListener(this);
        } else {
            itemView.setEnabled(false);
            itemView.setOnClickListener(null);
        }
    }

    @Override
    public void onClick(View view) {

    }


    private void setStatusLabelMultipleStyles() {
        final int flag = android.text.Spannable.SPAN_EXCLUSIVE_EXCLUSIVE;
        int start;
        int end;
        android.text.SpannableStringBuilder text = new android.text.SpannableStringBuilder();

        start = text.length();
        text.append("Mac");
        end = text.length();
        text.setSpan(new android.text.style.TypefaceSpan("sans-serif"), start, end, flag);
        text.setSpan(new android.text.style.StyleSpan(android.graphics.Typeface.NORMAL), start, end, flag);
        text.setSpan(new android.text.style.AbsoluteSizeSpan((int)12, true), start, end, flag);
        text.setSpan(new android.text.style.AlignmentSpan.Standard(android.text.Layout.Alignment.ALIGN_NORMAL), start, end, flag);
        text.setSpan(new android.text.style.ForegroundColorSpan(0xFF939396), start, end, flag);

        start = text.length();
        text.append("微信已登录，手机通知已关闭");
        end = text.length();
        text.setSpan(new android.text.style.TypefaceSpan("sans-serif"), start, end, flag);
        text.setSpan(new android.text.style.StyleSpan(android.graphics.Typeface.NORMAL), start, end, flag);
        text.setSpan(new android.text.style.AbsoluteSizeSpan((int)12, true), start, end, flag);
        text.setSpan(new android.text.style.AlignmentSpan.Standard(android.text.Layout.Alignment.ALIGN_NORMAL), start, end, flag);
        text.setSpan(new android.text.style.ForegroundColorSpan(0xFF939396), start, end, flag);
        mStatusLabel.setText(text);
    }

}

class ConversationListLoginStatusCellData {
    private String mStatusLabel;
    private String mCellId;
    private boolean mClickable;
    private String mStatusImage;

    public String getStatusLabel() {
        return mStatusLabel;
    }

    public void setStatusLabel(String statusLabel) {
        mStatusLabel = statusLabel;
    }
    public String getCellId() {
        return mCellId;
    }

    public void setCellId(String cellId) {
        mCellId = cellId;
    }
    public boolean getClickable() {
        return mClickable;
    }

    public void setClickable(boolean clickable) {
        mClickable = clickable;
    }
    public String getStatusImage() {
        return mStatusImage;
    }

    public void setStatusImage(String statusImage) {
        mStatusImage = statusImage;
    }
}
