package org.lianxianghui.weixindemo.weixin.conversationlist;

import android.os.Bundle;
import androidx.fragment.app.Fragment;
import androidx.fragment.app.FragmentManager;
import androidx.appcompat.app.AppCompatActivity;
import org.lianxianghui.weixindemo.R;

/**
* Generated by Sketch2Code
* Created by lianxianghui on 21-08-18.
*/

public class ConversationListActivity extends AppCompatActivity {
    private static final String TAG = "ConversationListActivity";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.conversation_list_activity);

        FragmentManager fm = getSupportFragmentManager();
        Fragment fragment = fm.findFragmentById(R.id.fragment_container);

        if (fragment == null) {
            fragment = new ConversationListFragment();
            fm.beginTransaction()
                .add(R.id.fragment_container, fragment)
                .commit();
        }
    }
}
