package org.lianxianghui.weixindemo.weixin.conversationlist;

import androidx.recyclerview.widget.RecyclerView;
import android.widget.Space;
import androidx.appcompat.widget.AppCompatTextView;
import android.content.Intent;
import androidx.core.graphics.drawable.RoundedBitmapDrawableFactory;
import androidx.appcompat.widget.AppCompatImageView;
import org.lianxianghui.weixindemo.R;
import androidx.core.graphics.drawable.RoundedBitmapDrawable;
import android.graphics.Bitmap;
import android.view.KeyEvent;
import android.view.LayoutInflater;
import android.graphics.BitmapFactory;
import android.view.View;
import android.widget.TextView;
import androidx.constraintlayout.widget.ConstraintLayout;
import android.view.ViewGroup;

/**
* Generated by Sketch2Code
* Created by lianxianghui on 21-08-18.
*/

public class ConversationListConversationCellViewHolder extends RecyclerView.ViewHolder {
    private ConversationListConversationCellData conversationListConversationCellData;

    public final View bottomLine;
    public final AppCompatImageView noDisturbingImage;
    public final AppCompatTextView time;
    public final AppCompatTextView latestMessage;
    public final AppCompatTextView title;
    public final AppCompatImageView leftImage;
    public final ConstraintLayout circle;
    public final Space pointForCenteryOfCircle;
    public final Space pointForCenterxOfCircle;
    public final Space pointForBottomOfTitleToTopOfLeftImage;

    public ConversationListConversationCellViewHolder(LayoutInflater inflater, ViewGroup parent) {
        super(inflater.inflate(R.layout.conversation_list_conversation_cell, parent, false));
        View v = itemView;
        bottomLine = v.findViewById(R.id.bottom_line);
        noDisturbingImage = (AppCompatImageView) v.findViewById(R.id.no_disturbing_image);
        time = (AppCompatTextView) v.findViewById(R.id.time);
        latestMessage = (AppCompatTextView) v.findViewById(R.id.latest_message);
        title = (AppCompatTextView) v.findViewById(R.id.title);
        leftImage = (AppCompatImageView) v.findViewById(R.id.left_image);
        circle = (ConstraintLayout) v.findViewById(R.id.circle);
        pointForCenteryOfCircle = (Space) v.findViewById(R.id.point_for_centery_of_circle);
        pointForCenterxOfCircle = (Space) v.findViewById(R.id.point_for_centerx_of_circle);
        pointForBottomOfTitleToTopOfLeftImage = (Space) v.findViewById(R.id.point_for_bottom_of_title_to_top_of_left_image);
    }

    public void bind(ConversationListConversationCellData conversationListConversationCellData) {
        this.conversationListConversationCellData = conversationListConversationCellData;
        time.setText(conversationListConversationCellData.getTime());
        latestMessage.setText(conversationListConversationCellData.getLatestMessage());
        title.setText(conversationListConversationCellData.getTitle());
        String imageName = conversationListConversationCellData.getNoDisturbingImage();
        if (imageName != null) {
            int noDisturbingImageResId = itemView.getResources().getIdentifier(imageName, "drawable", "org.lianxianghui.weixindemo");
            if (noDisturbingImageResId != 0)
                noDisturbingImage.setImageResource(noDisturbingImageResId);
        }
        imageName = conversationListConversationCellData.getLeftImage();
        if (imageName != null) {
            int leftImageResId = itemView.getResources().getIdentifier(imageName, "drawable", "org.lianxianghui.weixindemo");
            if (leftImageResId != 0)
                leftImage.setImageResource(leftImageResId);
        }
        boolean clickable = conversationListConversationCellData.getClickable();
        if (clickable) {
            itemView.setEnabled(true);
        } else {
            itemView.setEnabled(false);
        }
        boolean hidden = conversationListConversationCellData.getNoDisturbingImageHidden();
        if (hidden)
            noDisturbingImage.setVisibility(View.INVISIBLE);
        else
            noDisturbingImage.setVisibility(View.VISIBLE);
        hidden = conversationListConversationCellData.getLatestMessageHidden();
        if (hidden)
            latestMessage.setVisibility(View.INVISIBLE);
        else
            latestMessage.setVisibility(View.VISIBLE);
        hidden = conversationListConversationCellData.getCircleHidden();
        if (hidden)
            circle.setVisibility(View.INVISIBLE);
        else
            circle.setVisibility(View.VISIBLE);
    }

    public ConversationListConversationCellData getConversationListConversationCellData() {
        return conversationListConversationCellData;
    }






}

class ConversationListConversationCellData {
    private String cellId;
    private boolean noDisturbingImageHidden;
    private String noDisturbingImage;
    private String time;
    private boolean latestMessageHidden;
    private String title;
    private String latestMessage;
    private boolean circleHidden;
    private boolean clickable;
    private String leftImage;

    public String getCellId() {
        return cellId;
    }
    public void setCellId(String cellId) {
        this.cellId = cellId;
    }

    public boolean getNoDisturbingImageHidden() {
        return noDisturbingImageHidden;
    }
    public void setNoDisturbingImageHidden(boolean noDisturbingImageHidden) {
        this.noDisturbingImageHidden = noDisturbingImageHidden;
    }

    public String getNoDisturbingImage() {
        return noDisturbingImage;
    }
    public void setNoDisturbingImage(String noDisturbingImage) {
        this.noDisturbingImage = noDisturbingImage;
    }

    public String getTime() {
        return time;
    }
    public void setTime(String time) {
        this.time = time;
    }

    public boolean getLatestMessageHidden() {
        return latestMessageHidden;
    }
    public void setLatestMessageHidden(boolean latestMessageHidden) {
        this.latestMessageHidden = latestMessageHidden;
    }

    public String getTitle() {
        return title;
    }
    public void setTitle(String title) {
        this.title = title;
    }

    public String getLatestMessage() {
        return latestMessage;
    }
    public void setLatestMessage(String latestMessage) {
        this.latestMessage = latestMessage;
    }

    public boolean getCircleHidden() {
        return circleHidden;
    }
    public void setCircleHidden(boolean circleHidden) {
        this.circleHidden = circleHidden;
    }

    public boolean getClickable() {
        return clickable;
    }
    public void setClickable(boolean clickable) {
        this.clickable = clickable;
    }

    public String getLeftImage() {
        return leftImage;
    }
    public void setLeftImage(String leftImage) {
        this.leftImage = leftImage;
    }

}
